import { cdn } from '@/lib/cdn';

export interface Ship {
  name: string;
  image: string;
}

export interface ShipManufacturer {
  name: string;
  ships: Ship[];
}

// Enhanced Ship interface with detailed information
export interface ShipDetails {
  name: string;                // Ship name
  manufacturer: string;        // Manufacturer name
  type?: string;               // Ship type/class (optional)
  size?: 'Snub' | 'Small' | 'Medium' | 'Large' | 'Sub-capital' | 'Capital'; // Ship size category
  role?: string[];             // Ship roles (can have multiple)
  image: string;               // Path to ship image
  crewRequirement?: number;    // Minimum crew required
  maxCrew?: number;            // Maximum crew capacity
  cargoCapacity?: number;      // Cargo capacity in SCU
  length?: number;             // Length in meters
  beam?: number;               // Width/beam in meters
  height?: number;             // Height in meters
  speedSCM?: number;           // Standard Combat Maneuvering speed
  speedBoost?: number;         // Boost speed
  mass?: number;               // Mass in kg
}

// Create a function to format the image name from the ship name
export const formatShipImageName = (shipName: string): string => {
  // Special case for San'tok.yāi
  if (shipName === "San'tok.yāi") {
    return "santokyai.png";
  }
  
  return shipName.toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[\.']/g, '')
    .replace(/\//g, '_')
    .replace(/[āáàäâã]/g, 'a')
    .replace(/[ēéèëê]/g, 'e')
    .replace(/[īíìïî]/g, 'i')
    .replace(/[ōóòöôõ]/g, 'o')
    .replace(/[ūúùüû]/g, 'u')
    .replace(/[ÿý]/g, 'y')
    + '.png';
};

// Function to get the correct image path with fallback
export const getShipImagePath = (ship: ShipDetails | string): string => {
  const shipName = typeof ship === 'string' ? ship : ship.name;
  
  // This is the crucial part - format exactly as used in userprofile
  const formattedName = shipName.toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[\.']/g, '')
    .replace(/\//g, '_')
    .replace(/[āáàäâã]/g, 'a')
    .replace(/[ēéèëê]/g, 'e')
    .replace(/[īíìïî]/g, 'i')
    .replace(/[ōóòöôõ]/g, 'o')
    .replace(/[ūúùüû]/g, 'u')
    .replace(/[ÿý]/g, 'y');
  
  // Return CDN-prefixed path
  return cdn(`/images/${formattedName}.png`);
};

// Direct image path formatting function for consistent use across the app
export const getDirectImagePath = (shipName: string): string => {
  const formattedName = shipName.toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[\.']/g, '')
    .replace(/\//g, '_')
    .replace(/[āáàäâã]/g, 'a')
    .replace(/[ēéèëê]/g, 'e')
    .replace(/[īíìïî]/g, 'i')
    .replace(/[ōóòöôõ]/g, 'o')
    .replace(/[ūúùüû]/g, 'u')
    .replace(/[ÿý]/g, 'y');
  
  return cdn(`/images/${formattedName}.png`);
};

// Comprehensive ship database with detailed information from Star Citizen Wiki
// Source: https://starcitizen.fandom.com/wiki/List_of_ships
export const shipDatabase: ShipDetails[] = [
  // ORIGIN JUMPWORKS
  {
    name: "100i",
    manufacturer: "Origin Jumpworks",
    type: "100i",
    size: "Small",
    role: ["Starter", "Touring"],
    image: getShipImagePath("100i"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 19.3,
    beam: 11.0,
    height: 4.0,
    speedSCM: 210,
  },
  {
    name: "125a",
    manufacturer: "Origin Jumpworks",
    type: "125a",
    size: "Small",
    role: ["Starter", "Light Fighter"],
    image: getShipImagePath("125a"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 19.3,
    beam: 11.0,
    height: 4.0,
    speedSCM: 230,
  },
  {
    name: "135c",
    manufacturer: "Origin Jumpworks",
    type: "135c",
    size: "Small",
    role: ["Starter", "Light Freight"],
    image: getShipImagePath("135c"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 6,
    length: 19.3,
    beam: 11.0,
    height: 4.0,
    speedSCM: 190,
  },
  {
    name: "300i",
    manufacturer: "Origin Jumpworks",
    type: "300i",
    size: "Small",
    role: ["Touring"],
    image: getShipImagePath("300i"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 8,
    length: 27.0,
    beam: 17.0,
    height: 8.0,
    mass: 66320,
    speedSCM: 204,
    speedBoost: 1190,
  },
  {
    name: "315p",
    manufacturer: "Origin Jumpworks",
    type: "315p",
    size: "Small",
    role: ["Pathfinder"],
    image: getShipImagePath("315p"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 12,
    length: 27.0,
    beam: 17.0,
    height: 8.0,
    mass: 69220,
    speedSCM: 210,
    speedBoost: 1225,
  },
  {
    name: "325a",
    manufacturer: "Origin Jumpworks",
    type: "325a",
    size: "Small",
    role: ["Interdiction", "Interception"],
    image: getShipImagePath("325a"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 4,
    length: 27.0,
    beam: 17.0,
    height: 8.0,
    mass: 81435,
    speedSCM: 225,
    speedBoost: 1315,
  },
  {
    name: "350r",
    manufacturer: "Origin Jumpworks",
    type: "350r",
    size: "Small",
    role: ["Racing"],
    image: getShipImagePath("350r"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 4,
    length: 27.0,
    beam: 17.0,
    height: 8.0,
    mass: 58530,
    speedSCM: 258,
    speedBoost: 1345,
  },
  {
    name: "400i",
    manufacturer: "Origin Jumpworks",
    type: "400i",
    size: "Medium",
    role: ["Pathfinder"],
    image: getShipImagePath("400i"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 42,
    length: 60.0,
    beam: 32.0,
    height: 12.5,
    mass: 455927,
    speedSCM: 184,
    speedBoost: 1249,
  },
  {
    name: "600i Explorer",
    manufacturer: "Origin Jumpworks",
    type: "600i Explorer",
    size: "Large",
    role: ["Exploration", "Multi-crew"],
    image: getShipImagePath("600i Explorer"),
    crewRequirement: 3,
    maxCrew: 5,
    cargoCapacity: 40,
    length: 91.5,
    beam: 52.0,
    height: 17.0,
    speedSCM: 155,
    speedBoost: 1110,
  },
  
  // AEGIS DYNAMICS
  {
    name: "Avenger Titan",
    manufacturer: "Aegis Dynamics",
    type: "Avenger Titan",
    size: "Small",
    role: ["Light Freight", "Light Fighter"],
    image: getShipImagePath("Avenger Titan"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 8,
    length: 22.5,
    beam: 16.5,
    height: 6.0,
    speedSCM: 220,
    speedBoost: 1115,
  },
  {
    name: "Gladius",
    manufacturer: "Aegis Dynamics",
    type: "Gladius",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Gladius"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 20.0,
    beam: 17.0,
    height: 5.5,
    speedSCM: 280,
    speedBoost: 1225,
  },
  {
    name: "Hammerhead",
    manufacturer: "Aegis Dynamics",
    type: "Hammerhead",
    size: "Large",
    role: ["Heavy Fighter", "Gunship"],
    image: getShipImagePath("Hammerhead"),
    crewRequirement: 3,
    maxCrew: 9,
    cargoCapacity: 40,
    length: 112.0,
    beam: 75.0,
    height: 16.0,
    speedSCM: 125,
    speedBoost: 750,
  },
  {
    name: "Sabre",
    manufacturer: "Aegis Dynamics",
    type: "Sabre",
    size: "Small",
    role: ["Medium Fighter", "Stealth"],
    image: getShipImagePath("Sabre"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 26.0,
    beam: 22.0,
    height: 5.0,
    speedSCM: 255,
    speedBoost: 1235,
  },
  {
    name: "Vanguard Warden",
    manufacturer: "Aegis Dynamics",
    type: "Vanguard Warden",
    size: "Medium",
    role: ["Heavy Fighter"],
    image: getShipImagePath("Vanguard Warden"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 38.0,
    beam: 26.5,
    height: 9.5,
    mass: 256409,
    speedSCM: 225,
    speedBoost: 1115,
  },
  {
    name: "Reclaimer",
    manufacturer: "Aegis Dynamics",
    type: "Reclaimer",
    size: "Large",
    role: ["Heavy Salvage"],
    image: getShipImagePath("Reclaimer"),
    crewRequirement: 4,
    maxCrew: 8,
    cargoCapacity: 180,
    length: 155.0,
    beam: 118.0,
    height: 47.0,
    speedSCM: 115,
    speedBoost: 645,
  },
  {
    name: "Redeemer",
    manufacturer: "Aegis Dynamics",
    type: "Redeemer",
    size: "Medium",
    role: ["Gunship"],
    image: getShipImagePath("Redeemer"),
    crewRequirement: 3,
    maxCrew: 5,
    cargoCapacity: 0,
    length: 37.5,
    beam: 19.5,
    height: 9.5,
    speedSCM: 170,
    speedBoost: 1005
  },
  {
    name: "Retaliator",
    manufacturer: "Aegis Dynamics",
    type: "Retaliator",
    size: "Large",
    role: ["Heavy Bomber"],
    image: getShipImagePath("Retaliator"),
    crewRequirement: 6,
    maxCrew: 7,
    cargoCapacity: 0,
    length: 69.0,
    beam: 38.0,
    height: 14.5,
    speedSCM: 145,
    speedBoost: 900
  },
  
  // ANVIL AEROSPACE
  {
    name: "Arrow",
    manufacturer: "Anvil Aerospace",
    type: "Arrow",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Arrow"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 16.0,
    beam: 12.0,
    height: 4.0,
    speedSCM: 270,
    speedBoost: 1235,
  },
  {
    name: "Hornet F7C",
    manufacturer: "Anvil Aerospace",
    type: "Hornet F7C",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("Hornet"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 22.5,
    beam: 23.5,
    height: 5.5,
    speedSCM: 270,
    speedBoost: 1115,
  },
  {
    name: "Carrack",
    manufacturer: "Anvil Aerospace",
    type: "Carrack",
    size: "Large",
    role: ["Expedition", "Exploration", "Pathfinder"],
    image: getShipImagePath("Carrack"),
    crewRequirement: 4,
    maxCrew: 6,
    cargoCapacity: 456,
    length: 126.5,
    beam: 76.5,
    height: 30.0,
    speedSCM: 127,
    speedBoost: 800,
  },
  {
    name: "Terrapin",
    manufacturer: "Anvil Aerospace",
    type: "Terrapin",
    size: "Small",
    role: ["Pathfinder"],
    image: getShipImagePath("Terrapin"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 19.5,
    beam: 14.5,
    height: 6.0,
    mass: 172378,
    speedSCM: 210,
    speedBoost: 1205,
  },
  
  // DRAKE INTERPLANETARY
  {
    name: "Cutlass Black",
    manufacturer: "Drake Interplanetary",
    type: "Cutlass Black",
    size: "Medium",
    role: ["Medium Fighter", "Medium Freight"],
    image: getShipImagePath("Cutlass Black"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 46,
    length: 29.0,
    beam: 26.5,
    height: 10.0,
    speedSCM: 250,
    speedBoost: 1115,
  },
  {
    name: "Cutlass Red",
    manufacturer: "Drake Interplanetary",
    type: "Cutlass Red",
    size: "Medium",
    role: ["Medical"],
    image: getShipImagePath("Cutlass Red"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 12,
    length: 29.0,
    beam: 26.5,
    height: 10.0,
    speedSCM: 220,
    speedBoost: 1005,
  },
  {
    name: "Cutlass Blue",
    manufacturer: "Drake Interplanetary",
    type: "Cutlass Blue",
    size: "Medium",
    role: ["Interdiction", "Bounty Hunting"],
    image: getShipImagePath("Cutlass Blue"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 12,
    length: 29.0,
    beam: 26.5,
    height: 10.0,
    speedSCM: 270,
    speedBoost: 1200,
  },
  {
    name: "Buccaneer",
    manufacturer: "Drake Interplanetary",
    type: "Buccaneer",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Buccaneer"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 17.0,
    beam: 17.0,
    height: 5.5,
    speedSCM: 270,
    speedBoost: 1250,
  },
  {
    name: "Herald",
    manufacturer: "Drake Interplanetary",
    type: "Herald",
    size: "Small",
    role: ["Data Runner", "Info Runner"],
    image: getShipImagePath("Herald"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 23.5,
    beam: 14.5,
    height: 7.0,
    speedSCM: 270,
    speedBoost: 1360,
  },
  {
    name: "Vulture",
    manufacturer: "Drake Interplanetary",
    type: "Vulture",
    size: "Small",
    role: ["Salvage"],
    image: getShipImagePath("Vulture"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 12,
    length: 27.5,
    beam: 16.5,
    height: 10.0,
    speedSCM: 210,
    speedBoost: 1145,
  },
  {
    name: "Caterpillar",
    manufacturer: "Drake Interplanetary",
    type: "Caterpillar",
    size: "Large",
    role: ["Industrial", "Medium Freight"],
    image: getShipImagePath("Caterpillar"),
    crewRequirement: 3,
    maxCrew: 7,
    cargoCapacity: 576,
    length: 111.5,
    beam: 39.0,
    height: 13.5,
    speedSCM: 125,
    speedBoost: 760,
  },
  {
    name: "Corsair",
    manufacturer: "Drake Interplanetary",
    type: "Corsair",
    size: "Medium",
    role: ["Exploration", "Gun Ship"],
    image: getShipImagePath("Corsair"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 72,
    length: 55.0,
    beam: 27.0,
    height: 14.0,
    speedSCM: 195,
    speedBoost: 1050,
  },
  
  // MISC
  {
    name: "Freelancer",
    manufacturer: "MISC",
    type: "Freelancer",
    size: "Medium",
    role: ["Medium Freight"],
    image: getShipImagePath("Freelancer"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 66,
    length: 38.0,
    beam: 23.5,
    height: 8.5,
    speedSCM: 205,
    speedBoost: 970,
  },
  {
    name: "Prospector",
    manufacturer: "MISC",
    type: "Prospector",
    size: "Small",
    role: ["Industrial", "Mining"],
    image: getShipImagePath("Prospector"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 32,
    length: 24.0,
    beam: 13.5,
    height: 7.0,
    speedSCM: 185,
    speedBoost: 900,
  },
  {
    name: "Starfarer",
    manufacturer: "MISC",
    type: "Starfarer",
    size: "Large",
    role: ["Industrial", "Refueling"],
    image: getShipImagePath("Starfarer"),
    crewRequirement: 6,
    maxCrew: 7,
    cargoCapacity: 295,
    length: 101.0,
    beam: 47.0,
    height: 25.0,
    speedSCM: 125,
    speedBoost: 750,
  },
  
  // RSI
  {
    name: "Aurora MR",
    manufacturer: "RSI",
    type: "Aurora MR",
    size: "Small",
    role: ["Starter", "Light Fighter"],
    image: getShipImagePath("Aurora MR"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 17.5,
    beam: 10.0,
    height: 4.0,
    speedSCM: 190,
    speedBoost: 1095,
  },
  {
    name: "Constellation Andromeda",
    manufacturer: "RSI",
    type: "Constellation Andromeda",
    size: "Large",
    role: ["Multi-crew", "Medium Freight"],
    image: getShipImagePath("Constellation Andromeda"),
    crewRequirement: 3,
    maxCrew: 5,
    cargoCapacity: 96,
    length: 61.0,
    beam: 26.0,
    height: 14.0,
    speedSCM: 155,
    speedBoost: 910,
  },
  {
    name: "Mantis",
    manufacturer: "RSI",
    type: "Mantis",
    size: "Small",
    role: ["Interdiction"],
    image: getShipImagePath("Mantis"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 30.0,
    beam: 16.0,
    height: 6.5,
    speedSCM: 210,
    speedBoost: 1220,
  },
  
  // CRUSADER INDUSTRIES
  {
    name: "Mercury Star Runner",
    manufacturer: "Crusader Industries",
    type: "Mercury Star Runner",
    size: "Medium",
    role: ["Medium Freight", "Data Runner"],
    image: getShipImagePath("Mercury Star Runner"),
    crewRequirement: 2,
    maxCrew: 3,
    cargoCapacity: 114,
    length: 40.0,
    beam: 40.0,
    height: 9.5,
    speedSCM: 215,
    speedBoost: 1180,
  },
  {
    name: "C2 Hercules Starlifter",
    manufacturer: "Crusader Industries",
    type: "C2 Hercules Starlifter",
    size: "Large",
    role: ["Heavy Freight"],
    image: getShipImagePath("C2 Hercules Starlifter"),
    crewRequirement: 2,
    maxCrew: 3,
    cargoCapacity: 696,
    length: 94.0,
    beam: 70.0,
    height: 23.0,
    speedSCM: 135,
    speedBoost: 900,
  },
  {
    name: "M2 Hercules Starlifter",
    manufacturer: "Crusader Industries",
    type: "M2 Hercules Starlifter",
    size: "Large",
    role: ["Heavy Freight", "Dropship"],
    image: getShipImagePath("M2 Hercules Starlifter"),
    crewRequirement: 2,
    maxCrew: 3,
    cargoCapacity: 522,
    length: 94.0,
    beam: 70.0,
    height: 23.0,
    speedSCM: 135,
    speedBoost: 900,
  },
  {
    name: "A2 Hercules Starlifter",
    manufacturer: "Crusader Industries",
    type: "A2 Hercules Starlifter",
    size: "Large",
    role: ["Bomber", "Dropship"],
    image: getShipImagePath("A2 Hercules Starlifter"),
    crewRequirement: 4,
    maxCrew: 8,
    cargoCapacity: 216,
    length: 94.0,
    beam: 70.0,
    height: 23.0,
    speedSCM: 135,
    speedBoost: 900,
  },
  
  // BANU
  {
    name: "Merchantman",
    manufacturer: "Banu",
    type: "Merchantman",
    size: "Large",
    role: ["Cargo", "Trading"],
    image: getShipImagePath("Merchantman"),
    crewRequirement: 8,
    maxCrew: 8,
    cargoCapacity: 3584,
    length: 160.0,
    beam: 160.0,
    height: 65.0,
    speedSCM: 95,
  },
  {
    name: "Defender",
    manufacturer: "Banu",
    type: "Defender",
    size: "Medium",
    role: ["Interdiction", "Fighter"],
    image: getShipImagePath("Defender"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 34.5,
    beam: 39.5,
    height: 9.5,
    speedSCM: 270,
  },
  // AEGIS DYNAMICS SECTION - Adding missing ships
  {
    name: "Avenger Stalker",
    manufacturer: "Aegis Dynamics",
    type: "Avenger Stalker",
    size: "Small",
    role: ["Interdiction"],
    image: getShipImagePath("Avenger Stalker"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 22.5,
    beam: 16.5,
    height: 5.5,
    speedSCM: 250,
    speedBoost: 1310
  },
  {
    name: "Avenger Titan Renegade",
    manufacturer: "Aegis Dynamics",
    type: "Avenger Titan Renegade",
    size: "Small",
    role: ["Light Freight"],
    image: getShipImagePath("Avenger Titan Renegade"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 8,
    length: 22.5,
    beam: 16.5,
    height: 5.5,
    speedSCM: 188,
    speedBoost: 1113
  },
  {
    name: "Avenger Warlock",
    manufacturer: "Aegis Dynamics",
    type: "Avenger Warlock",
    size: "Small",
    role: ["Interdiction"],
    image: getShipImagePath("Avenger Warlock"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 22.5,
    beam: 16.5,
    height: 5.5,
    speedSCM: 240,
    speedBoost: 1305
  },
  {
    name: "Eclipse",
    manufacturer: "Aegis Dynamics",
    type: "Eclipse",
    size: "Medium",
    role: ["Stealth Bomber"],
    image: getShipImagePath("Eclipse"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 20.5,
    beam: 36.6,
    height: 4.4,
    speedSCM: 195,
    speedBoost: 980
  },
  {
    name: "Gladius Pirate",
    manufacturer: "Aegis Dynamics",
    type: "Gladius Pirate",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Gladius Pirate"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 20.0,
    beam: 17.0,
    height: 5.5,
    speedSCM: 207,
    speedBoost: 1235
  },
  {
    name: "Gladius Valiant",
    manufacturer: "Aegis Dynamics",
    type: "Gladius Valiant",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Gladius Valiant"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 20.0,
    beam: 17.0,
    height: 5.5,
    speedSCM: 207,
    speedBoost: 1235
  },
  {
    name: "Hammerhead Best In Show Edition",
    manufacturer: "Aegis Dynamics",
    type: "Hammerhead Best In Show Edition",
    size: "Large",
    role: ["Heavy Gunship"],
    image: getShipImagePath("Hammerhead Best In Show Edition"),
    crewRequirement: 3,
    maxCrew: 8,
    cargoCapacity: 40,
    length: 115.0,
    beam: 75.0,
    height: 16.0,
    speedSCM: 125,
    speedBoost: 750
  },
  {
    name: "Idris-K",
    manufacturer: "Aegis Dynamics",
    type: "Idris-K",
    size: "Capital",
    role: ["Frigate"],
    image: getShipImagePath("Idris-K"),
    crewRequirement: 8,
    maxCrew: 28,
    cargoCapacity: 831,
    length: 242.0,
    beam: 126.0,
    height: 46.0
  },
  {
    name: "Idris-M",
    manufacturer: "Aegis Dynamics",
    type: "Idris-M",
    size: "Capital",
    role: ["Frigate"],
    image: getShipImagePath("Idris-M"),
    crewRequirement: 8,
    maxCrew: 28,
    cargoCapacity: 831,
    length: 242.0,
    beam: 126.0,
    height: 46.0,
    mass: 37866540
  },
  {
    name: "Idris-P",
    manufacturer: "Aegis Dynamics",
    type: "Idris-P",
    size: "Capital",
    role: ["Frigate"],
    image: getShipImagePath("Idris-P"),
    crewRequirement: 8,
    maxCrew: 28,
    cargoCapacity: 995,
    length: 233.0,
    beam: 126.0,
    height: 46.0,
    mass: 37310200
  },
  {
    name: "Javelin",
    manufacturer: "Aegis Dynamics",
    type: "Javelin",
    size: "Capital",
    role: ["Destroyer"],
    image: getShipImagePath("Javelin"),
    crewRequirement: 12,
    maxCrew: 80,
    cargoCapacity: 5400,
    length: 480.0,
    beam: 198.0,
    height: 72.0,
    mass: 109860179
  },
  {
    name: "Nautilus",
    manufacturer: "Aegis Dynamics",
    type: "Nautilus",
    size: "Large",
    role: ["Minelayer"],
    image: getShipImagePath("Nautilus"),
    crewRequirement: 4,
    maxCrew: 8,
    cargoCapacity: 64,
    length: 125.0,
    beam: 72.0,
    height: 21.6,
    speedSCM: 115,
    mass: 13526320
  },
  {
    name: "Reclaimer Best In Show Edition",
    manufacturer: "Aegis Dynamics",
    type: "Reclaimer Best In Show Edition",
    size: "Large",
    role: ["Heavy Salvage"],
    image: getShipImagePath("Reclaimer Best In Show Edition"),
    crewRequirement: 4,
    maxCrew: 5,
    cargoCapacity: 180,
    length: 155.0,
    beam: 118.0,
    height: 50.0,
    speedSCM: 100,
    speedBoost: 930,
    mass: 9500158
  },
  {
    name: "Sabre Comet",
    manufacturer: "Aegis Dynamics",
    type: "Sabre Comet",
    size: "Small",
    role: ["Stealth Fighter"],
    image: getShipImagePath("Sabre Comet"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 24.0,
    beam: 26.0,
    height: 5.0,
    speedSCM: 215,
    speedBoost: 1235,
    mass: 78513
  },
  {
    name: "Sabre Firebird",
    manufacturer: "Aegis Dynamics",
    type: "Sabre Firebird",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("Sabre Firebird"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 26.0,
    beam: 30.0,
    height: 3.8,
    speedSCM: 240,
    speedBoost: 1400,
    mass: 78513
  },
  {
    name: "Sabre Peregrine",
    manufacturer: "Aegis Dynamics",
    type: "Sabre Peregrine",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("Sabre Peregrine"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 24.0,
    beam: 26.0,
    height: 5.0,
    speedSCM: 275,
    speedBoost: 1235
  },
  {
    name: "Sabre Raven",
    manufacturer: "Aegis Dynamics",
    type: "Sabre Raven",
    size: "Small",
    role: ["Interdiction"],
    image: getShipImagePath("Sabre Raven"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 24.0,
    beam: 20.5,
    height: 5.0,
    speedSCM: 275,
    speedBoost: 1235,
    mass: 69433
  },
  {
    name: "Vanguard Harbinger",
    manufacturer: "Aegis Dynamics",
    type: "Vanguard Harbinger",
    size: "Medium",
    role: ["Bomber"],
    image: getShipImagePath("Vanguard Harbinger"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 38.0,
    beam: 26.5,
    height: 9.5,
    mass: 240092
  },
  {
    name: "Vanguard Hoplite",
    manufacturer: "Aegis Dynamics",
    type: "Vanguard Hoplite",
    size: "Medium",
    role: ["Dropship"],
    image: getShipImagePath("Vanguard Hoplite"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 38.0,
    beam: 26.5,
    height: 9.5,
    speedSCM: 230,
    speedBoost: 1020,
    mass: 229440
  },
  {
    name: "Vanguard Sentinel",
    manufacturer: "Aegis Dynamics",
    type: "Vanguard Sentinel",
    size: "Medium",
    role: ["Interdiction"],
    image: getShipImagePath("Vanguard Sentinel"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 38.0,
    beam: 26.5,
    height: 9.5,
    mass: 238616
  },
  {
    name: "Vulcan",
    manufacturer: "Aegis Dynamics",
    type: "Vulcan",
    size: "Medium",
    role: ["Medium Repair", "Medium Refuel"],
    image: getShipImagePath("Vulcan"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 12,
    length: 38.5,
    beam: 16.5,
    height: 10.0,
    speedSCM: 210,
    mass: 625330
  },
  // ANVIL AEROSPACE - Adding missing ships
  {
    name: "Ballista",
    manufacturer: "Anvil Aerospace",
    type: "Ballista",
    size: "Small",
    role: ["Ground Vehicle", "Anti-Aircraft"],
    image: getShipImagePath("Ballista"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 0,
    length: 16.0,
    beam: 7.5,
    height: 6.0
  },
  {
    name: "Ballista Dunestalker",
    manufacturer: "Anvil Aerospace",
    type: "Ballista Dunestalker",
    size: "Small",
    role: ["Ground Vehicle", "Anti-Aircraft"],
    image: getShipImagePath("Ballista Dunestalker"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 0,
    length: 16.0,
    beam: 7.5,
    height: 6.0
  },
  {
    name: "Ballista Snowblind",
    manufacturer: "Anvil Aerospace",
    type: "Ballista Snowblind",
    size: "Small",
    role: ["Ground Vehicle", "Anti-Aircraft"],
    image: getShipImagePath("Ballista Snowblind"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 0,
    length: 16.0,
    beam: 7.5,
    height: 6.0
  },
  {
    name: "C8R Pisces Rescue",
    manufacturer: "Anvil Aerospace",
    type: "C8R Pisces Rescue",
    size: "Small",
    role: ["Medical"],
    image: getShipImagePath("C8R Pisces Rescue"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 0,
    length: 13.0,
    beam: 10.0,
    height: 3.2,
    speedSCM: 164
  },
  {
    name: "C8X Pisces Expedition",
    manufacturer: "Anvil Aerospace",
    type: "C8X Pisces Expedition",
    size: "Small",
    role: ["Exploration"],
    image: getShipImagePath("C8X Pisces Expedition"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 4,
    length: 13.0,
    beam: 10.0,
    height: 3.2,
    speedSCM: 140
  },
  {
    name: "Carrack Expedition",
    manufacturer: "Anvil Aerospace",
    type: "Carrack Expedition",
    size: "Large",
    role: ["Expedition"],
    image: getShipImagePath("Carrack Expedition"),
    crewRequirement: 4,
    maxCrew: 6,
    cargoCapacity: 456,
    length: 126.5,
    beam: 76.5,
    height: 30.0,
    speedSCM: 208,
    speedBoost: 1076,
    mass: 4397858
  },
  {
    name: "Centurion",
    manufacturer: "Anvil Aerospace",
    type: "Centurion",
    size: "Small",
    role: ["Anti-Aircraft"],
    image: getShipImagePath("Centurion"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 24.0,
    beam: 18.0,
    height: 7.0
  },
  {
    name: "Crucible",
    manufacturer: "Anvil Aerospace",
    type: "Crucible",
    size: "Large",
    role: ["Heavy Repair"],
    image: getShipImagePath("Crucible"),
    crewRequirement: 3,
    maxCrew: 8,
    cargoCapacity: 230,
    length: 90.0,
    beam: 50.0,
    height: 20.0,
    mass: 3650500
  },
  {
    name: "F7C Hornet Mk I",
    manufacturer: "Anvil Aerospace",
    type: "F7C Hornet Mk I",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("F7C Hornet Mk I"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 22.5,
    beam: 21.5,
    height: 6.5,
    speedSCM: 235,
    speedBoost: 1225,
    mass: 73535
  },
  {
    name: "F7C Hornet Mk II",
    manufacturer: "Anvil Aerospace",
    type: "F7C Hornet Mk II",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("F7C Hornet Mk II"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 22.5,
    beam: 21.5,
    height: 6.5,
    speedSCM: 235,
    speedBoost: 1225,
    mass: 73535
  },
  {
    name: "F7C Hornet Wildfire Mk I",
    manufacturer: "Anvil Aerospace",
    type: "F7C Hornet Wildfire Mk I",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("F7C Hornet Wildfire Mk I"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 22.5,
    beam: 21.5,
    height: 6.5,
    speedSCM: 185,
    speedBoost: 1224,
    mass: 73535
  },
  {
    name: "F7C-M Hornet Heartseeker Mk II",
    manufacturer: "Anvil Aerospace",
    type: "F7C-M Hornet Heartseeker Mk II",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("F7C-M Hornet Heartseeker Mk II"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 25.5,
    beam: 24.0,
    height: 6.5,
    speedSCM: 230,
    speedBoost: 1220,
    mass: 78466
  },
  {
    name: "F7C-M Super Hornet Heartseeker Mk I",
    manufacturer: "Anvil Aerospace",
    type: "F7C-M Super Hornet Heartseeker Mk I",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("F7C-M Super Hornet Heartseeker Mk I"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 25.5,
    beam: 24.0,
    height: 6.5,
    speedSCM: 230,
    speedBoost: 1220,
    mass: 78466
  },
  {
    name: "F7C-M Super Hornet Mk I",
    manufacturer: "Anvil Aerospace",
    type: "F7C-M Super Hornet Mk I",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("F7C-M Super Hornet Mk I"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 25.5,
    beam: 24.0,
    height: 6.5,
    speedSCM: 230,
    speedBoost: 1220,
    mass: 78466
  },
  {
    name: "F7C M Super Hornet Mk II",
    manufacturer: "Anvil Aerospace",
    type: "F7C M Super Hornet Mk II",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("F7C M Super Hornet Mk II"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 25.5,
    beam: 24.0,
    height: 6.5,
    speedSCM: 230,
    speedBoost: 1220,
    mass: 78466
  },
  {
    name: "F7C-R Hornet Tracker Mk I",
    manufacturer: "Anvil Aerospace",
    type: "F7C-R Hornet Tracker Mk I",
    size: "Small",
    role: ["Pathfinder"],
    image: getShipImagePath("F7C-R Hornet Tracker Mk I"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 22.5,
    beam: 21.5,
    height: 6.5,
    speedSCM: 240,
    speedBoost: 1215,
    mass: 73497
  },
  {
    name: "F7C-R Hornet Tracker Mk II",
    manufacturer: "Anvil Aerospace",
    type: "F7C-R Hornet Tracker Mk II",
    size: "Small",
    role: ["Pathfinder"],
    image: getShipImagePath("F7C-R Hornet Tracker Mk II"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 22.5,
    beam: 21.5,
    height: 6.5,
    speedSCM: 240,
    speedBoost: 1215,
    mass: 73497
  },
  {
    name: "F7C-S Hornet Ghost Mk I",
    manufacturer: "Anvil Aerospace",
    type: "F7C-S Hornet Ghost Mk I",
    size: "Small",
    role: ["Stealth Fighter"],
    image: getShipImagePath("F7C-S Hornet Ghost Mk I"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 22.5,
    beam: 21.5,
    height: 6.5,
    speedSCM: 235,
    speedBoost: 1225,
    mass: 73454
  },
  {
    name: "F7C-S Hornet Ghost Mk II",
    manufacturer: "Anvil Aerospace",
    type: "F7C-S Hornet Ghost Mk II",
    size: "Small",
    role: ["Stealth Fighter"],
    image: getShipImagePath("F7C-S Hornet Ghost Mk II"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 22.5,
    beam: 21.5,
    height: 6.5,
    speedSCM: 235,
    speedBoost: 1225,
    mass: 73454
  },
  {
    name: "F8C Lightening",
    manufacturer: "Anvil Aerospace",
    type: "F8C Lightening",
    size: "Small",
    role: ["Heavy Fighter"],
    image: getShipImagePath("F8C Lightening"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 24.0,
    beam: 24.0,
    height: 6.5,
    mass: 161236
  },
  {
    name: "Gladiator",
    manufacturer: "Anvil Aerospace",
    type: "Gladiator",
    size: "Small",
    role: ["Bomber"],
    image: getShipImagePath("Gladiator"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 22.5,
    beam: 22.5,
    height: 6.0,
    speedSCM: 200,
    speedBoost: 980,
    mass: 87497
  },
  {
    name: "Hawk",
    manufacturer: "Anvil Aerospace",
    type: "Hawk",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Hawk"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 17.0,
    beam: 22.0,
    height: 6.5,
    speedSCM: 200,
    speedBoost: 500,
    mass: 40000
  },
  {
    name: "Hurricane",
    manufacturer: "Anvil Aerospace",
    type: "Hurricane",
    size: "Small",
    role: ["Heavy Fighter"],
    image: getShipImagePath("Hurricane"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 22.0,
    beam: 14.5,
    height: 6.0,
    speedSCM: 265,
    speedBoost: 1125,
    mass: 86454
  },
  {
    name: "Legionnaire",
    manufacturer: "Anvil Aerospace",
    type: "Legionnaire",
    size: "Small",
    role: ["Boarding ship"],
    image: getShipImagePath("Legionnaire"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 32.0,
    beam: 23.3,
    height: 10.2
  },
  {
    name: "Liberator",
    manufacturer: "Anvil Aerospace",
    type: "Liberator",
    size: "Large",
    role: ["Transporter"],
    image: getShipImagePath("Liberator"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 400,
    length: 119.0,
    beam: 67.0,
    height: 25.0,
    speedSCM: 115
  },
  {
    name: "Paladin",
    manufacturer: "Anvil Aerospace",
    type: "Paladin",
    size: "Large",
    role: ["Military"],
    image: getShipImagePath("Paladin"),
    crewRequirement: 2,
    maxCrew: 5,
    cargoCapacity: 0,
    length: 60.0,
    beam: 40.0,
    height: 15.0
  },
  {
    name: "Spartan",
    manufacturer: "Anvil Aerospace",
    type: "Spartan",
    size: "Small",
    role: ["Ground Vehicle", "Personnel Transport"],
    image: getShipImagePath("Spartan"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 16.5,
    beam: 8.5,
    height: 6.0
  },
  {
    name: "Terrapin Medic",
    manufacturer: "Anvil Aerospace",
    type: "Terrapin Medic",
    size: "Small",
    role: ["Pathfinder", "Medical"],
    image: getShipImagePath("Terrapin Medic"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 19.5,
    beam: 14.5,
    height: 6.0,
    speedSCM: 210,
    speedBoost: 1205,
    mass: 172378
  },
  {
    name: "Valkyrie",
    manufacturer: "Anvil Aerospace",
    type: "Valkyrie",
    size: "Small",
    role: ["Military", "Industrial"],
    image: getShipImagePath("Valkyrie"),
    crewRequirement: 2,
    maxCrew: 5,
    cargoCapacity: 30,
    length: 38.0,
    beam: 28.0,
    height: 9.5,
    speedSCM: 205,
    mass: 75000
  },
  {
    name: "Valkyrie Liberator",
    manufacturer: "Anvil Aerospace",
    type: "Valkyrie Liberator",
    size: "Small",
    role: ["Military", "Industrial"],
    image: getShipImagePath("Valkyrie Liberator"),
    crewRequirement: 2,
    maxCrew: 5,
    cargoCapacity: 30,
    length: 38.0,
    beam: 28.0,
    height: 9.5,
    speedSCM: 205,
    mass: 75000
  },
  
  // AOPOA SHIPS
  {
    name: "Blade",
    manufacturer: "Aopoa",
    type: "Blade",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Blade"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 16.5,
    beam: 20.0,
    height: 5.5,
    speedSCM: 290,
    speedBoost: 1240,
    mass: 26056
  },
  {
    name: "Khartu-al",
    manufacturer: "Aopoa",
    type: "Khartu-al",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Khartu-al"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 31.5,
    beam: 12.5,
    height: 8.5,
    speedSCM: 300,
    speedBoost: 1325,
    mass: 67115
  },
  {
    name: "Nox",
    manufacturer: "Aopoa",
    type: "Nox",
    size: "Small",
    role: ["Ground Vehicle", "Racing"],
    image: getShipImagePath("Nox"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 6.0,
    beam: 2.5,
    height: 1.5
  },
  {
    name: "Nox Kue",
    manufacturer: "Aopoa",
    type: "Nox Kue",
    size: "Small",
    role: ["Ground Vehicle", "Racing"],
    image: getShipImagePath("Nox Kue"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 6.0,
    beam: 2.5,
    height: 1.5
  },
  {
    name: "San'tok.yāi",
    manufacturer: "Aopoa",
    type: "San'tok.yāi",
    size: "Medium",
    role: ["Medium Fighter"],
    image: getShipImagePath("San'tok.yāi"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 24.0,
    beam: 23.0,
    height: 10.0,
    speedSCM: 265,
    mass: 106566
  },
  {
    name: "Scythe",
    manufacturer: "Aopoa",
    type: "Scythe",
    size: "Small",
    role: ["Medium Fighter"],
    image: getShipImagePath("Scythe"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 31.0,
    beam: 23.0,
    height: 8.5,
    speedSCM: 194,
    speedBoost: 1230,
    mass: 73942
  },
  
  // ARGO ASTRONAUTICS SHIPS
  {
    name: "ATLS",
    manufacturer: "Argo Astronautics",
    type: "ATLS",
    size: "Small",
    role: ["Ground Vehicle", "Transport"],
    image: getShipImagePath("ATLS"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 8.0,
    beam: 4.0,
    height: 3.0
  },
  {
    name: "ATLS GEO",
    manufacturer: "Argo Astronautics",
    type: "ATLS GEO",
    size: "Small",
    role: ["Ground Vehicle", "Transport"],
    image: getShipImagePath("ATLS GEO"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 8.0,
    beam: 4.0,
    height: 3.0
  },
  {
    name: "CSV-SM",
    manufacturer: "Argo Astronautics",
    type: "CSV-SM",
    size: "Small",
    role: ["Support"],
    image: getShipImagePath("CSV-SM"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 18.0,
    beam: 10.0,
    height: 6.0
  },
  {
    name: "MPUV Cargo",
    manufacturer: "Argo Astronautics",
    type: "MPUV Cargo",
    size: "Snub",
    role: ["Light Freight"],
    image: getShipImagePath("MPUV Cargo"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 9.5,
    beam: 8.5,
    height: 4.3,
    speedSCM: 150,
    speedBoost: 900,
    mass: 12187
  },
  {
    name: "MPUV Personnel",
    manufacturer: "Argo Astronautics",
    type: "MPUV Personnel",
    size: "Snub",
    role: ["Passenger"],
    image: getShipImagePath("MPUV Personnel"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 9.3,
    beam: 8.5,
    height: 4.3,
    speedSCM: 150,
    speedBoost: 920,
    mass: 12307
  },
  {
    name: "MPUV Tractor",
    manufacturer: "Argo Astronautics",
    type: "MPUV Tractor",
    size: "Snub",
    role: ["Industrial"],
    image: getShipImagePath("MPUV Tractor"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 9.5,
    beam: 8.5,
    height: 4.3,
    speedSCM: 150,
    speedBoost: 900
  },
  {
    name: "MOLE",
    manufacturer: "Argo Astronautics",
    type: "MOLE",
    size: "Medium",
    role: ["Prospecting and Mining"],
    image: getShipImagePath("MOLE"),
    crewRequirement: 1,
    maxCrew: 4,
    cargoCapacity: 288,
    length: 45.0,
    beam: 25.0,
    height: 15.0,
    speedSCM: 127,
    speedBoost: 1089
  },
  {
    name: "MOLE Carbon",
    manufacturer: "Argo Astronautics",
    type: "MOLE Carbon",
    size: "Medium",
    role: ["Prospecting and Mining"],
    image: getShipImagePath("MOLE Carbon"),
    crewRequirement: 1,
    maxCrew: 4,
    cargoCapacity: 288,
    length: 45.0,
    beam: 25.0,
    height: 15.0,
    speedSCM: 127,
    speedBoost: 1089
  },
  {
    name: "MOLE Talus",
    manufacturer: "Argo Astronautics",
    type: "MOLE Talus",
    size: "Medium",
    role: ["Prospecting and Mining"],
    image: getShipImagePath("MOLE Talus"),
    crewRequirement: 1,
    maxCrew: 4,
    cargoCapacity: 288,
    length: 45.0,
    beam: 25.0,
    height: 15.0,
    speedSCM: 127,
    speedBoost: 1089
  },
  {
    name: "RAFT",
    manufacturer: "Argo Astronautics",
    type: "RAFT",
    size: "Medium",
    role: ["Medium Freight"],
    image: getShipImagePath("RAFT"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 96,
    length: 39.5,
    beam: 23.0,
    height: 12.0,
    speedSCM: 134,
    speedBoost: 839,
    mass: 1183478
  },
  {
    name: "SRV",
    manufacturer: "Argo Astronautics",
    type: "SRV",
    size: "Small",
    role: ["Industrial", "Civilian"],
    image: getShipImagePath("SRV"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 10,
    length: 28.5,
    beam: 19.5,
    height: 8.7,
    speedSCM: 200,
    mass: 231680
  },
  // CNOU (CONSOLIDATED OUTLAND) SHIPS
  {
    name: "HoverQuad",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "HoverQuad",
    size: "Small",
    role: ["Ground Vehicle", "Racing"],
    image: getShipImagePath("HoverQuad"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 4.0,
    beam: 2.0,
    height: 1.0
  },
  {
    name: "Nomad",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Nomad",
    size: "Small",
    role: ["Light Freight"],
    image: getShipImagePath("Nomad"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 24,
    length: 26.5,
    beam: 18.3,
    height: 9.2,
    speedSCM: 180,
    speedBoost: 1171,
    mass: 228123
  },
  {
    name: "Pioneer",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Pioneer",
    size: "Large",
    role: ["Industrial"],
    image: getShipImagePath("Pioneer"),
    crewRequirement: 4,
    maxCrew: 8,
    cargoCapacity: 230,
    length: 125.0,
    beam: 68.0,
    height: 40.0
  },
  {
    name: "Mustang Alpha",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Mustang Alpha",
    size: "Small",
    role: ["Cargo"],
    image: getShipImagePath("Mustang Alpha"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 4,
    length: 21.5,
    beam: 18.0,
    height: 9.0,
    speedSCM: 255,
    speedBoost: 1160,
    mass: 32970
  },
  {
    name: "Mustang Alpha Vindicator",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Mustang Alpha Vindicator",
    size: "Small",
    role: ["Starter", "Light Freight"],
    image: getShipImagePath("Mustang Alpha Vindicator"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 4,
    length: 17.5,
    beam: 15.5,
    height: 5.5,
    speedSCM: 255,
    speedBoost: 1160,
    mass: 32970
  },
  {
    name: "Mustang Beta",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Mustang Beta",
    size: "Small",
    role: ["Pathfinder"],
    image: getShipImagePath("Mustang Beta"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 21.5,
    beam: 18.0,
    height: 9.0,
    speedSCM: 250,
    speedBoost: 1215,
    mass: 39610
  },
  {
    name: "Mustang Delta",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Mustang Delta",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Mustang Delta"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 21.0,
    beam: 18.0,
    height: 9.0,
    speedSCM: 240,
    speedBoost: 1225,
    mass: 37345
  },
  {
    name: "Mustang Gamma",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Mustang Gamma",
    size: "Small",
    role: ["Racing"],
    image: getShipImagePath("Mustang Gamma"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 21.5,
    beam: 18.0,
    height: 9.0,
    speedSCM: 325,
    speedBoost: 1340,
    mass: 30263
  },
  {
    name: "Mustang Omega",
    manufacturer: "CNOU (Consolidated Outland)",
    type: "Mustang Omega",
    size: "Small",
    role: ["Racing"],
    image: getShipImagePath("Mustang Omega"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 21.5,
    beam: 18.0,
    height: 9.0,
    speedSCM: 325,
    speedBoost: 1340,
    mass: 30263
  },
  // CRUSADER INDUSTRIES SHIPS
  {
    name: "A1 Spirit",
    manufacturer: "Crusader Industries",
    type: "A1 Spirit",
    size: "Medium",
    role: ["Bomber", "Attack"],
    image: getShipImagePath("A1 Spirit"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 0,
    length: 47.5,
    beam: 44.0,
    height: 10.0,
    speedSCM: 195
  },
  {
    name: "Ares Star Fighter Inferno",
    manufacturer: "Crusader Industries",
    type: "Ares Star Fighter Inferno",
    size: "Medium",
    role: ["Heavy Combat Fighter"],
    image: getShipImagePath("Ares Star Fighter Inferno"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 27.2,
    beam: 30.2,
    height: 5.5,
    speedSCM: 170,
    speedBoost: 818,
    mass: 343455
  },
  {
    name: "Ares Star Fighter Ion",
    manufacturer: "Crusader Industries",
    type: "Ares Star Fighter Ion",
    size: "Medium",
    role: ["Heavy Combat Fighter"],
    image: getShipImagePath("Ares Star Fighter Ion"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 27.2,
    beam: 30.2,
    height: 5.5,
    speedSCM: 170,
    speedBoost: 818,
    mass: 342195
  },
  {
    name: "C1 Spirit",
    manufacturer: "Crusader Industries",
    type: "C1 Spirit",
    size: "Medium",
    role: ["Medium Freight"],
    image: getShipImagePath("C1 Spirit"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 64,
    length: 47.5,
    beam: 44.0,
    height: 10.0,
    speedSCM: 204,
    speedBoost: 405,
    mass: 314271
  },
  {
    name: "E1 Spirit",
    manufacturer: "Crusader Industries",
    type: "E1 Spirit",
    size: "Medium",
    role: ["Exploration"],
    image: getShipImagePath("E1 Spirit"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 20,
    length: 47.5,
    beam: 44.0,
    height: 10.0,
    speedSCM: 200
  },
  {
    name: "Genesis Starliner",
    manufacturer: "Crusader Industries",
    type: "Genesis Starliner",
    size: "Large",
    role: ["Passenger"],
    image: getShipImagePath("Genesis Starliner"),
    crewRequirement: 2,
    maxCrew: 8,
    cargoCapacity: 300,
    length: 85.0,
    beam: 90.0,
    height: 16.0,
    mass: 3120000
  },
  {
    name: "Intrepid",
    manufacturer: "Crusader Industries",
    type: "Intrepid",
    size: "Large",
    role: ["Search and Rescue"],
    image: getShipImagePath("Intrepid"),
    crewRequirement: 3,
    maxCrew: 8,
    cargoCapacity: 85,
    length: 125.0,
    beam: 70.0,
    height: 30.0
  },
  // ESPERIA SHIPS
  {
    name: "Glaive",
    manufacturer: "Esperia",
    type: "Glaive",
    size: "Medium",
    role: ["Medium Fighter"],
    image: getShipImagePath("Glaive"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 31.0,
    beam: 31.5,
    height: 8.5,
    speedSCM: 255,
    speedBoost: 1230,
    mass: 66013
  },
  {
    name: "Prowler",
    manufacturer: "Esperia",
    type: "Prowler",
    size: "Medium",
    role: ["Dropship"],
    image: getShipImagePath("Prowler"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 34.0,
    beam: 33.0,
    height: 15.0,
    speedSCM: 178,
    speedBoost: 1116,
    mass: 171700
  },
  {
    name: "Talon",
    manufacturer: "Esperia",
    type: "Talon",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Talon"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 20.0,
    beam: 18.0,
    height: 5.0,
    speedSCM: 250,
    speedBoost: 1235,
    mass: 60836
  },
  {
    name: "Talon Shrike",
    manufacturer: "Esperia",
    type: "Talon Shrike",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Talon Shrike"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 20.0,
    beam: 18.0,
    height: 5.0,
    speedSCM: 250,
    speedBoost: 1235,
    mass: 60836
  },
  
  // GATAC MANUFACTURE SHIPS
  {
    name: "Railen",
    manufacturer: "Gatac Manufacture",
    type: "Railen",
    size: "Medium",
    role: ["Cargo"],
    image: getShipImagePath("Railen"),
    crewRequirement: 1,
    maxCrew: 4,
    cargoCapacity: 320,
    length: 53.0,
    beam: 52.0,
    height: 67.0
  },
  {
    name: "Syulen",
    manufacturer: "Gatac Manufacture",
    type: "Syulen",
    size: "Medium",
    role: ["Industrial"],
    image: getShipImagePath("Syulen"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 120,
    length: 40.0,
    beam: 30.0,
    height: 15.0
  },
  // GREYCAT INDUSTRIAL SHIPS
  {
    name: "MTC",
    manufacturer: "Greycat Industrial",
    type: "MTC",
    size: "Small",
    role: ["Ground Vehicle", "Transport"],
    image: getShipImagePath("MTC"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 6.5,
    beam: 4.0,
    height: 2.5
  },
  {
    name: "PTV",
    manufacturer: "Greycat Industrial",
    type: "PTV",
    size: "Small",
    role: ["Ground Vehicle", "Transport"],
    image: getShipImagePath("PTV"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 4.0,
    beam: 2.5,
    height: 1.5
  },
  {
    name: "ROC",
    manufacturer: "Greycat Industrial",
    type: "ROC",
    size: "Small",
    role: ["Ground Vehicle", "Mining"],
    image: getShipImagePath("ROC"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0.8,
    length: 6.0,
    beam: 3.5,
    height: 2.5
  },
  {
    name: "ROC-DS",
    manufacturer: "Greycat Industrial",
    type: "ROC-DS",
    size: "Small",
    role: ["Ground Vehicle", "Mining"],
    image: getShipImagePath("ROC-DS"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 1.6,
    length: 7.5,
    beam: 4.0,
    height: 3.0
  },
  {
    name: "STV",
    manufacturer: "Greycat Industrial",
    type: "STV",
    size: "Small",
    role: ["Ground Vehicle", "Transport"],
    image: getShipImagePath("STV"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0.75,
    length: 5.5,
    beam: 3.0,
    height: 2.0
  },
  {
    name: "Ursa",
    manufacturer: "Greycat Industrial",
    type: "Ursa",
    size: "Small",
    role: ["Ground Vehicle", "Transport", "Combat"],
    image: getShipImagePath("Ursa"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 2,
    length: 8.0,
    beam: 5.0,
    height: 3.0
  },
  {
    name: "Ursa Fortuna",
    manufacturer: "Greycat Industrial",
    type: "Ursa Fortuna",
    size: "Small",
    role: ["Ground Vehicle", "Transport", "Combat"],
    image: getShipImagePath("Ursa Fortuna"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 2,
    length: 8.0,
    beam: 5.0,
    height: 3.0
  },
  {
    name: "Ursa Medivac",
    manufacturer: "Greycat Industrial",
    type: "Ursa Medivac",
    size: "Small",
    role: ["Ground Vehicle", "Medical"],
    image: getShipImagePath("Ursa Medivac"),
    crewRequirement: 1,
    maxCrew: 3,
    cargoCapacity: 0,
    length: 8.0,
    beam: 5.0,
    height: 3.0
  },
  
  // KRUGER INTERGALACTIC SHIPS
  {
    name: "P-52 Merlin",
    manufacturer: "Kruger Intergalatic",
    type: "P-52 Merlin",
    size: "Snub",
    role: ["Snub Fighter"],
    image: getShipImagePath("P-52 Merlin"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 12.0,
    beam: 7.7,
    height: 2.2,
    speedSCM: 270,
    speedBoost: 1030,
    mass: 8493
  },
  {
    name: "P-72 Archimedes",
    manufacturer: "Kruger Intergalatic",
    type: "P-72 Archimedes",
    size: "Snub",
    role: ["Racing"],
    image: getShipImagePath("P-72 Archimedes"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 12.0,
    beam: 7.7,
    height: 2.2,
    speedSCM: 250,
    mass: 8290
  },
  {
    name: "P-72 Archimedes Emerald",
    manufacturer: "Kruger Intergalatic",
    type: "P-72 Archimedes Emerald",
    size: "Snub",
    role: ["Racing"],
    image: getShipImagePath("P-72 Archimedes Emerald"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 12.0,
    beam: 7.7,
    height: 2.2,
    speedSCM: 250,
    mass: 8290
  },
  // DRAKE INTERPLANETARY SHIPS
  {
    name: "Caterpillar Best In Show Edition",
    manufacturer: "Drake Interplanetary",
    type: "Caterpillar Best In Show Edition",
    size: "Large",
    role: ["Transport"],
    image: getShipImagePath("Caterpillar Best In Show Edition"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 576,
    length: 111.5,
    beam: 39.0,
    height: 13.5,
    speedSCM: 130,
    speedBoost: 890,
    mass: 1608205
  },
  {
    name: "Caterpillar Pirate Edition",
    manufacturer: "Drake Interplanetary",
    type: "Caterpillar Pirate Edition",
    size: "Large",
    role: ["Transport"],
    image: getShipImagePath("Caterpillar Pirate Edition"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 564,
    length: 111.5,
    beam: 39.0,
    height: 13.5,
    speedSCM: 130,
    speedBoost: 890,
    mass: 1608205
  },
  {
    name: "Cutlass Black Best In Show Edition",
    manufacturer: "Drake Interplanetary",
    type: "Cutlass Black Best In Show Edition",
    size: "Medium",
    role: ["Medium Fighter", "Medium Freight"],
    image: getShipImagePath("Cutlass Black Best In Show Edition"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 46,
    length: 29.0,
    beam: 26.5,
    height: 10.0,
    speedSCM: 220,
    speedBoost: 1115,
    mass: 226700
  },
  {
    name: "Cutlass Steel",
    manufacturer: "Drake Interplanetary",
    type: "Cutlass Steel",
    size: "Medium",
    role: ["Dropship"],
    image: getShipImagePath("Cutlass Steel"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 8,
    length: 29.0,
    beam: 26.5,
    height: 10.0,
    speedSCM: 220,
    speedBoost: 1115
  },
  {
    name: "Cutter",
    manufacturer: "Drake Interplanetary",
    type: "Cutter",
    size: "Small",
    role: ["Light Freight"],
    image: getShipImagePath("Cutter"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 4,
    length: 20.0,
    beam: 13.0,
    height: 6.0,
    speedSCM: 180,
    speedBoost: 1010,
    mass: 70000
  },
  {
    name: "Cutter Rambler",
    manufacturer: "Drake Interplanetary",
    type: "Cutter Rambler",
    size: "Small",
    role: ["Light Freight"],
    image: getShipImagePath("Cutter Rambler"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 20.0,
    beam: 13.0,
    height: 6.0,
    speedSCM: 185,
    speedBoost: 1015
  },
  {
    name: "Cutter Scout",
    manufacturer: "Drake Interplanetary",
    type: "Cutter Scout",
    size: "Small",
    role: ["Light Freight", "Exploration"],
    image: getShipImagePath("Cutter Scout"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 20.0,
    beam: 13.0,
    height: 6.0,
    speedSCM: 185,
    speedBoost: 1015
  },
  {
    name: "Dragonfly",
    manufacturer: "Drake Interplanetary",
    type: "Dragonfly",
    size: "Small",
    role: ["Ground Vehicle"],
    image: getShipImagePath("Dragonfly"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 1,
    length: 6.0,
    beam: 2.5,
    height: 1.5,
    speedSCM: 60
  },
  {
    name: "Dragonfly Yellowjacket",
    manufacturer: "Drake Interplanetary",
    type: "Dragonfly Yellowjacket",
    size: "Small",
    role: ["Ground Vehicle"],
    image: getShipImagePath("Dragonfly Yellowjacket"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 1,
    length: 6.0,
    beam: 2.5,
    height: 1.5,
    speedSCM: 60
  },
  {
    name: "Golem",
    manufacturer: "Drake Interplanetary",
    type: "Golem",
    size: "Large",
    role: ["Industrial", "Salvage"],
    image: getShipImagePath("Golem"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 350,
    length: 75.0,
    beam: 40.0,
    height: 20.0
  },
  {
    name: "Ironclad",
    manufacturer: "Drake Interplanetary",
    type: "Ironclad",
    size: "Medium",
    role: ["Combat"],
    image: getShipImagePath("Ironclad"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 12,
    length: 35.0,
    beam: 25.0,
    height: 12.0
  },
  {
    name: "Ironclad Assault",
    manufacturer: "Drake Interplanetary",
    type: "Ironclad Assault",
    size: "Medium",
    role: ["Combat"],
    image: getShipImagePath("Ironclad Assault"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 8,
    length: 35.0,
    beam: 25.0,
    height: 12.0
  },
  {
    name: "Kraken",
    manufacturer: "Drake Interplanetary",
    type: "Kraken",
    size: "Capital",
    role: ["Multi-Role - Light Carrier"],
    image: getShipImagePath("Kraken"),
    crewRequirement: 10,
    maxCrew: 10,
    cargoCapacity: 3792,
    length: 270.0,
    beam: 104.0,
    height: 64.0
  },
  {
    name: "Kraken Privateer",
    manufacturer: "Drake Interplanetary",
    type: "Kraken Privateer",
    size: "Capital",
    role: ["Multi-Role - Light Carrier"],
    image: getShipImagePath("Kraken Privateer"),
    crewRequirement: 10,
    maxCrew: 10,
    cargoCapacity: 768,
    length: 270.0,
    beam: 104.0,
    height: 64.0
  },
  {
    name: "Mule",
    manufacturer: "Drake Interplanetary",
    type: "Mule",
    size: "Small",
    role: ["Ground Vehicle", "Transport", "Cargo"],
    image: getShipImagePath("Mule"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 2,
    length: 6.5,
    beam: 4.0,
    height: 3.0
  },
  // MISC SHIPS
  {
    name: "Freelancer DUR",
    manufacturer: "MISC",
    type: "Freelancer DUR",
    size: "Medium",
    role: ["Expedition"],
    image: getShipImagePath("Freelancer DUR"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 36,
    length: 38.0,
    beam: 23.5,
    height: 9.5,
    speedSCM: 205,
    speedBoost: 1005,
    mass: 213680
  },
  {
    name: "Freelancer MAX",
    manufacturer: "MISC",
    type: "Freelancer MAX",
    size: "Medium",
    role: ["Medium Freight"],
    image: getShipImagePath("Freelancer MAX"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 120,
    length: 38.0,
    beam: 36.0,
    height: 9.5,
    speedSCM: 195,
    speedBoost: 985,
    mass: 336230
  },
  {
    name: "Freelancer MIS",
    manufacturer: "MISC",
    type: "Freelancer MIS",
    size: "Medium",
    role: ["Gunship"],
    image: getShipImagePath("Freelancer MIS"),
    crewRequirement: 2,
    maxCrew: 4,
    cargoCapacity: 36,
    length: 38.0,
    beam: 23.5,
    height: 9.5,
    speedSCM: 205,
    speedBoost: 1005,
    mass: 213680
  },
  {
    name: "Hull A",
    manufacturer: "MISC",
    type: "Hull A",
    size: "Small",
    role: ["Medium Freight"],
    image: getShipImagePath("Hull A"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 64,
    length: 22.0,
    beam: 8.0,
    height: 4.0,
    mass: 122650
  },
  {
    name: "Hull B",
    manufacturer: "MISC",
    type: "Hull B",
    size: "Medium",
    role: ["Heavy Freight"],
    image: getShipImagePath("Hull B"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 384,
    length: 49.0,
    beam: 15.5,
    height: 17.0,
    mass: 387500
  },
  {
    name: "Hull C",
    manufacturer: "MISC",
    type: "Hull C",
    size: "Large",
    role: ["Heavy Freight"],
    image: getShipImagePath("Hull C"),
    crewRequirement: 2,
    maxCrew: 3,
    cargoCapacity: 4608,
    length: 105.0,
    beam: 35.0,
    height: 35.0
  },
  {
    name: "Hull D",
    manufacturer: "MISC",
    type: "Hull D",
    size: "Capital",
    role: ["Heavy Freight"],
    image: getShipImagePath("Hull D"),
    crewRequirement: 3,
    maxCrew: 5,
    cargoCapacity: 20736,
    length: 209.0,
    beam: 70.0,
    height: 70.0,
    mass: 1216000
  },
  {
    name: "Hull E",
    manufacturer: "MISC",
    type: "Hull E",
    size: "Capital",
    role: ["Heavy Freight"],
    image: getShipImagePath("Hull E"),
    crewRequirement: 4,
    maxCrew: 5,
    cargoCapacity: 98304,
    length: 372.0,
    beam: 104.0,
    height: 104.0,
    mass: 1652000
  },
  {
    name: "Endeavor",
    manufacturer: "MISC",
    type: "Endeavor",
    size: "Capital",
    role: ["Heavy Science"],
    image: getShipImagePath("Endeavor"),
    crewRequirement: 3,
    maxCrew: 5,
    cargoCapacity: 500,
    length: 200.0,
    beam: 48.0,
    height: 20.0,
    mass: 4055000
  },
  {
    name: "Odyssey",
    manufacturer: "MISC",
    type: "Odyssey",
    size: "Large",
    role: ["Expedition"],
    image: getShipImagePath("Odyssey"),
    crewRequirement: 1,
    maxCrew: 6,
    cargoCapacity: 252,
    length: 140.0,
    beam: 90.0,
    height: 35.0
  },
  {
    name: "Razor",
    manufacturer: "MISC",
    type: "Razor",
    size: "Small",
    role: ["Racing"],
    image: getShipImagePath("Razor"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 11.5,
    beam: 8.2,
    height: 2.7,
    speedSCM: 335,
    speedBoost: 1345,
    mass: 10925
  },
  {
    name: "Razor EX",
    manufacturer: "MISC",
    type: "Razor EX",
    size: "Small",
    role: ["Stealth"],
    image: getShipImagePath("Razor EX"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 11.5,
    beam: 8.2,
    height: 2.7,
    speedSCM: 325,
    speedBoost: 1340,
    mass: 10925
  },
  {
    name: "Razor LX",
    manufacturer: "MISC",
    type: "Razor LX",
    size: "Small",
    role: ["Luxury"],
    image: getShipImagePath("Razor LX"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 11.5,
    beam: 8.2,
    height: 2.7,
    speedSCM: 340,
    speedBoost: 1345,
    mass: 10925
  },
  {
    name: "Reliant Kore",
    manufacturer: "MISC",
    type: "Reliant Kore",
    size: "Small",
    role: ["Starter", "Light Freight"],
    image: getShipImagePath("Reliant Kore"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 6,
    length: 14.5,
    beam: 28.5,
    height: 4.0,
    speedSCM: 220,
    speedBoost: 1150,
    mass: 38566
  },
  {
    name: "Reliant Mako",
    manufacturer: "MISC",
    type: "Reliant Mako",
    size: "Small",
    role: ["Reporting"],
    image: getShipImagePath("Reliant Mako"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 14.5,
    beam: 28.5,
    height: 4.0,
    speedSCM: 220,
    speedBoost: 1150,
    mass: 38566
  },
  {
    name: "Reliant Sen",
    manufacturer: "MISC",
    type: "Reliant Sen",
    size: "Small",
    role: ["Light Science"],
    image: getShipImagePath("Reliant Sen"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 2,
    length: 14.5,
    beam: 28.5,
    height: 4.0,
    speedSCM: 220,
    speedBoost: 1150,
    mass: 38566
  },
  {
    name: "Reliant Tana",
    manufacturer: "MISC",
    type: "Reliant Tana",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Reliant Tana"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 1,
    length: 14.5,
    beam: 28.5,
    height: 4.0,
    speedSCM: 220,
    speedBoost: 1150,
    mass: 38566
  },
  {
    name: "Starfarer Gemini",
    manufacturer: "MISC",
    type: "Starfarer Gemini",
    size: "Large",
    role: ["Heavy Refuelling"],
    image: getShipImagePath("Starfarer Gemini"),
    crewRequirement: 4,
    maxCrew: 6,
    cargoCapacity: 291,
    length: 101.0,
    beam: 46.5,
    height: 23.5,
    speedSCM: 115,
    speedBoost: 750,
    mass: 3517864
  },
  {
    name: "Expanse",
    manufacturer: "MISC",
    type: "Expanse",
    size: "Medium",
    role: ["Mining"],
    image: getShipImagePath("Expanse"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 32,
    length: 32.0,
    beam: 15.0,
    height: 7.5
  },
  {
    name: "Fortune",
    manufacturer: "MISC",
    type: "Fortune",
    size: "Small",
    role: ["Exploration"],
    image: getShipImagePath("Fortune"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 12,
    length: 22.0,
    beam: 14.0,
    height: 6.0
  },
  {
    name: "Starlancer MAX",
    manufacturer: "MISC",
    type: "Starlancer MAX",
    size: "Medium",
    role: ["Medium Freight"],
    image: getShipImagePath("Starlancer MAX"),
    crewRequirement: 2,
    maxCrew: 3,
    cargoCapacity: 72,
    length: 45.0,
    beam: 25.0,
    height: 12.0
  },
  {
    name: "Starlancer TAC",
    manufacturer: "MISC",
    type: "Starlancer TAC",
    size: "Medium",
    role: ["Combat"],
    image: getShipImagePath("Starlancer TAC"),
    crewRequirement: 2,
    maxCrew: 3,
    cargoCapacity: 36,
    length: 45.0,
    beam: 25.0,
    height: 12.0
  },
  
  // ORIGIN JUMPWORKS SHIPS
  {
    name: "600i Touring",
    manufacturer: "Origin Jumpworks",
    type: "600i Touring",
    size: "Large",
    role: ["Touring"],
    image: getShipImagePath("600i Touring"),
    crewRequirement: 3,
    maxCrew: 5,
    cargoCapacity: 16,
    length: 91.5,
    beam: 52.0,
    height: 17.0,
    speedSCM: 135,
    speedBoost: 950,
    mass: 1576792
  },
  {
    name: "85x",
    manufacturer: "Origin Jumpworks",
    type: "85x",
    size: "Small",
    role: ["Touring"],
    image: getShipImagePath("85x"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 13.0,
    beam: 10.0,
    height: 2.0,
    speedSCM: 255,
    speedBoost: 1185,
    mass: 19097
  },
  {
    name: "890 Jump",
    manufacturer: "Origin Jumpworks",
    type: "890 Jump",
    size: "Capital",
    role: ["Touring"],
    image: getShipImagePath("890 Jump"),
    crewRequirement: 3,
    maxCrew: 5,
    cargoCapacity: 484,
    length: 210.0,
    beam: 71.0,
    height: 40.0,
    speedSCM: 80,
    mass: 44246556
  },
  {
    name: "M50",
    manufacturer: "Origin Jumpworks",
    type: "M50",
    size: "Small",
    role: ["Racing"],
    image: getShipImagePath("M50"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 11.0,
    beam: 10.0,
    height: 3.0,
    speedSCM: 330,
    speedBoost: 1345,
    mass: 10580
  },
  {
    name: "X1",
    manufacturer: "Origin Jumpworks",
    type: "X1",
    size: "Small",
    role: ["Racing", "Ground Vehicle"],
    image: getShipImagePath("X1"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 5.5,
    beam: 2.0,
    height: 1.5
  },
  {
    name: "X1 Force",
    manufacturer: "Origin Jumpworks",
    type: "X1 Force",
    size: "Small",
    role: ["Combat", "Ground Vehicle"],
    image: getShipImagePath("X1 Force"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 5.5,
    beam: 2.0,
    height: 1.5
  },
  {
    name: "X1 Velocity",
    manufacturer: "Origin Jumpworks",
    type: "X1 Velocity",
    size: "Small",
    role: ["Racing", "Ground Vehicle"],
    image: getShipImagePath("X1 Velocity"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 5.5,
    beam: 2.0,
    height: 1.5
  },
  // RSI (ROBERTS SPACE INDUSTRIES) SHIPS
  {
    name: "Apollo Medivac",
    manufacturer: "RSI",
    type: "Apollo Medivac",
    size: "Large",
    role: ["Support - Medical"],
    image: getShipImagePath("Apollo Medivac"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 28,
    length: 43.0,
    beam: 30.0,
    height: 10.0,
    speedSCM: 195,
    mass: 376500
  },
  {
    name: "Apollo Triage",
    manufacturer: "RSI",
    type: "Apollo Triage",
    size: "Large",
    role: ["Support - Medical"],
    image: getShipImagePath("Apollo Triage"),
    crewRequirement: 2,
    maxCrew: 2,
    cargoCapacity: 28,
    length: 43.0,
    beam: 30.0,
    height: 10.0,
    speedSCM: 205,
    mass: 376500
  },
  {
    name: "Arrastra",
    manufacturer: "RSI",
    type: "Arrastra",
    size: "Medium",
    role: ["Mining"],
    image: getShipImagePath("Arrastra"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 24,
    length: 28.0,
    beam: 17.0,
    height: 8.0
  },
  {
    name: "Aurora CL",
    manufacturer: "RSI",
    type: "Aurora CL",
    size: "Small",
    role: ["Light Freight"],
    image: getShipImagePath("Aurora CL"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 6,
    length: 18.0,
    beam: 8.0,
    height: 4.0,
    speedSCM: 185,
    speedBoost: 1095,
    mass: 25172
  },
  {
    name: "Aurora ES",
    manufacturer: "RSI",
    type: "Aurora ES",
    size: "Small",
    role: ["Starter", "Pathfinder"],
    image: getShipImagePath("Aurora ES"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 18.0,
    beam: 8.0,
    height: 4.0,
    speedSCM: 190,
    speedBoost: 1140,
    mass: 25172
  },
  {
    name: "Aurora LN",
    manufacturer: "RSI",
    type: "Aurora LN",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Aurora LN"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 18.0,
    beam: 8.0,
    height: 4.0,
    speedSCM: 185,
    speedBoost: 1210,
    mass: 25338
  },
  {
    name: "Aurora LX",
    manufacturer: "RSI",
    type: "Aurora LX",
    size: "Small",
    role: ["Pathfinder"],
    image: getShipImagePath("Aurora LX"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 18.0,
    beam: 8.0,
    height: 4.0,
    speedSCM: 190,
    speedBoost: 1200,
    mass: 25017
  },
  {
    name: "Constellation Aquila",
    manufacturer: "RSI",
    type: "Constellation Aquila",
    size: "Large",
    role: ["Expedition"],
    image: getShipImagePath("Constellation Aquila"),
    crewRequirement: 3,
    maxCrew: 4,
    cargoCapacity: 96,
    length: 61.0,
    beam: 26.0,
    height: 14.0,
    speedSCM: 190,
    speedBoost: 985,
    mass: 453823
  },
  {
    name: "Constellation Phoenix",
    manufacturer: "RSI",
    type: "Constellation Phoenix",
    size: "Large",
    role: ["Touring"],
    image: getShipImagePath("Constellation Phoenix"),
    crewRequirement: 3,
    maxCrew: 4,
    cargoCapacity: 96,
    length: 61.0,
    beam: 26.0,
    height: 14.0,
    mass: 417510
  },
  {
    name: "Constellation Phoenix Emerald",
    manufacturer: "RSI",
    type: "Constellation Phoenix Emerald",
    size: "Large",
    role: ["Touring"],
    image: getShipImagePath("Constellation Phoenix Emerald"),
    crewRequirement: 3,
    maxCrew: 4,
    cargoCapacity: 96,
    length: 61.0,
    beam: 26.0,
    height: 14.0,
    mass: 417510
  },
  {
    name: "Constellation Taurus",
    manufacturer: "RSI",
    type: "Constellation Taurus",
    size: "Large",
    role: ["Medium Freight"],
    image: getShipImagePath("Constellation Taurus"),
    crewRequirement: 3,
    maxCrew: 4,
    cargoCapacity: 174,
    length: 61.0,
    beam: 26.0,
    height: 14.0,
    speedSCM: 190,
    mass: 431529
  },
  {
    name: "Galaxy",
    manufacturer: "RSI",
    type: "Galaxy",
    size: "Large",
    role: ["Exploration"],
    image: getShipImagePath("Galaxy"),
    crewRequirement: 3,
    maxCrew: 6,
    cargoCapacity: 120,
    length: 75.0,
    beam: 30.0,
    height: 15.0
  },
  {
    name: "Lynx",
    manufacturer: "RSI",
    type: "Lynx",
    size: "Small",
    role: ["Ground Vehicle", "Rover"],
    image: getShipImagePath("Lynx"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 3,
    length: 7.0,
    beam: 4.0,
    height: 2.5
  },
  {
    name: "Orion",
    manufacturer: "RSI",
    type: "Orion",
    size: "Capital",
    role: ["Heavy Mining"],
    image: getShipImagePath("Orion"),
    crewRequirement: 4,
    maxCrew: 7,
    cargoCapacity: 384,
    length: 170.0,
    beam: 50.0,
    height: 50.0,
    mass: 26496000
  },
  {
    name: "Perseus",
    manufacturer: "RSI",
    type: "Perseus",
    size: "Sub-capital",
    role: ["Gun-Boat"],
    image: getShipImagePath("Perseus"),
    crewRequirement: 6,
    maxCrew: 6,
    cargoCapacity: 50,
    length: 100.0,
    beam: 50.0,
    height: 21.0,
    speedSCM: 92
  },
  {
    name: "Polaris",
    manufacturer: "RSI",
    type: "Polaris",
    size: "Capital",
    role: ["Corvette"],
    image: getShipImagePath("Polaris"),
    crewRequirement: 6,
    maxCrew: 14,
    cargoCapacity: 216,
    length: 155.0,
    beam: 115.0,
    height: 35.0
  },
  {
    name: "Scorpius",
    manufacturer: "RSI",
    type: "Scorpius",
    size: "Small",
    role: ["Heavy Fighter"],
    image: getShipImagePath("Scorpius"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 24.5,
    beam: 33.0,
    height: 13.0
  },
  {
    name: "Scorpius Antares",
    manufacturer: "RSI",
    type: "Scorpius Antares",
    size: "Small",
    role: ["Heavy Fighter"],
    image: getShipImagePath("Scorpius Antares"),
    crewRequirement: 1,
    maxCrew: 2,
    cargoCapacity: 0,
    length: 24.5,
    beam: 33.0,
    height: 13.0
  },
  {
    name: "Zeus Mk II CL",
    manufacturer: "RSI",
    type: "Zeus Mk II CL",
    size: "Small",
    role: ["Light Freight"],
    image: getShipImagePath("Zeus Mk II CL"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 6,
    length: 19.0,
    beam: 9.0,
    height: 5.0
  },
  {
    name: "Zeus Mk II ES",
    manufacturer: "RSI",
    type: "Zeus Mk II ES",
    size: "Small",
    role: ["Starter", "Pathfinder"],
    image: getShipImagePath("Zeus Mk II ES"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 19.0,
    beam: 9.0,
    height: 5.0
  },
  {
    name: "Zeus Mk II MR",
    manufacturer: "RSI",
    type: "Zeus Mk II MR",
    size: "Small",
    role: ["Starter", "Light Fighter"],
    image: getShipImagePath("Zeus Mk II MR"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 19.0,
    beam: 9.0,
    height: 5.0
  },
  {
    name: "Zeus Mk II MR",
    manufacturer: "RSI",
    type: "Zeus Mk II MR",
    size: "Small",
    role: ["Starter", "Light Fighter"],
    image: getShipImagePath("Zeus Mk II MR"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 19.0,
    beam: 9.0,
    height: 5.0
  },
  // Add missing RSI ships
  {
    name: "Aurora MR",
    manufacturer: "RSI",
    type: "Aurora MR",
    size: "Small",
    role: ["Light Fighter"],
    image: getShipImagePath("Aurora MR"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 3,
    length: 18.0,
    beam: 8.0,
    height: 4.0,
    speedSCM: 195,
    speedBoost: 1210,
    mass: 28697
  },
  {
    name: "Bengal",
    manufacturer: "RSI",
    type: "Bengal",
    size: "Capital",
    role: ["Fleet carrier"],
    image: getShipImagePath("Bengal"),
    length: 990.0
  },
  {
    name: "Constellation Andromeda",
    manufacturer: "RSI",
    type: "Constellation Andromeda",
    size: "Large",
    role: ["Medium Freight", "Gunship"],
    image: getShipImagePath("Constellation Andromeda"),
    crewRequirement: 3,
    maxCrew: 4,
    cargoCapacity: 96,
    length: 61.0,
    beam: 26.0,
    height: 14.0,
    speedSCM: 190,
    speedBoost: 910,
    mass: 436531
  },
  {
    name: "Mantis",
    manufacturer: "RSI",
    type: "Mantis",
    size: "Small",
    role: ["Military", "Stealth"],
    image: getShipImagePath("Mantis"),
    crewRequirement: 1,
    maxCrew: 1,
    cargoCapacity: 0,
    length: 30.0,
    beam: 17.0,
    height: 8.0,
    speedSCM: 168,
    speedBoost: 1220,
    mass: 225621
  },
  {
    name: "Pegasus",
    manufacturer: "RSI",
    type: "Pegasus",
    size: "Capital",
    role: ["Escort Carrier"],
    image: getShipImagePath("Pegasus")
  },
];

// Ship manufacturers in the game
export const MANUFACTURERS = {
  AEGIS: "Aegis Dynamics",
  ANVIL: "Anvil Aerospace",
  AOPOA: "AopoA",
  ARGO: "Argo Astronautics",
  BANU: "Banu",
  CONSOLIDATED: "Consolidated Outland",
  CRUSADER: "Crusader Industries",
  DRAKE: "Drake Interplanetary",
  ESPERIA: "Esperia",
  GATAC: "Gatac Manufacture",
  GREYCAT: "Greycat Industrial",
  KRUGER: "Kruger Intergalactic",
  MISC: "MISC",
  ORIGIN: "Origin Jumpworks",
  RSI: "Roberts Space Industries",
  TUMBRIL: "Tumbril Land Systems",
  VANDUUL: "Vanduul"
};

// Helper function to ensure that every ship has proper type field matching the name
// This will fix the "Unknown Type" issue
export const ensureShipTypes = () => {
  shipDatabase.forEach(ship => {
    if (!ship.type) {
      ship.type = ship.name;
    }
  });
};

// Call this immediately to fix all ships
ensureShipTypes();

// Function to remove duplicate ships from the database
export const removeDuplicateShips = () => {
  try {
    const initialCount = shipDatabase.length;
    
    // Create a map to identify duplicates (case-insensitive)
    const uniqueShips: Record<string, ShipDetails> = {};
    const duplicates: string[] = [];
    
    // First pass: identify all duplicates
    for (const ship of shipDatabase) {
      const normalizedName = ship.name.toLowerCase();
      
      if (uniqueShips[normalizedName]) {
        duplicates.push(ship.name);
      } else {
        uniqueShips[normalizedName] = ship;
      }
    }
    
    // If duplicates were found, remove them
    if (duplicates.length > 0) {
      // In development, we can log this information
      if (process.env.NODE_ENV === 'development') {
        console.log(`Before deduplication: ${initialCount} ships`);
        console.log(`Found ${duplicates.length} duplicate ships`);
      }
      
      // Create a new array with only unique ships
      const deduplicatedShips = Object.values(uniqueShips);
      
      // Replace the original database with the deduplicated one
      shipDatabase.length = 0;
      deduplicatedShips.forEach(ship => shipDatabase.push(ship));
      
      // In development, we can log this information
      if (process.env.NODE_ENV === 'development') {
        console.log(`After deduplication: ${shipDatabase.length} ships`);
      }
    }
    
    return shipDatabase.length;
  } catch (error) {
    // Don't crash the application if deduplication fails
    console.error('Error during ship deduplication:', error);
    return shipDatabase.length;
  }
};

// Call the deduplication function right away
try {
  removeDuplicateShips();
} catch (error) {
  // Fail silently in production
  if (process.env.NODE_ENV === 'development') {
    console.error('Failed to deduplicate ships:', error);
  }
}

// Ensure lookup by name works for all ships
export const getShipByName = (name: string): ShipDetails | undefined => {
  if (!name) return undefined;
  const normalizedName = name.toLowerCase().trim();
  
  // Try direct match on name first
  const directMatch = shipDatabase.find(ship => 
    ship.name.toLowerCase() === normalizedName
  );
  
  if (directMatch) return directMatch;
  
  // If no direct match, try more flexible matching
  return shipDatabase.find(ship => 
    ship.name.toLowerCase() === normalizedName || 
    (ship.type && ship.type.toLowerCase() === normalizedName) ||
    ship.name.toLowerCase().includes(normalizedName) ||
    normalizedName.includes(ship.name.toLowerCase())
  );
};

export const getDetailedShipsByManufacturer = (manufacturer: string): ShipDetails[] => {
  if (!manufacturer) return [];
  const normalizedManufacturer = manufacturer.toLowerCase().trim();
  return shipDatabase.filter(ship => 
    ship.manufacturer.toLowerCase().includes(normalizedManufacturer)
  );
};

export const getShipsByType = (type: string): ShipDetails[] => {
  if (!type) return [];
  const normalizedType = type.toLowerCase().trim();
  return shipDatabase.filter(ship => 
    (ship.type && ship.type.toLowerCase().includes(normalizedType)) ||
    ship.name.toLowerCase().includes(normalizedType)
  );
};

export const getShipsBySize = (size: string): ShipDetails[] => {
  if (!size) return [];
  const normalizedSize = size.toLowerCase().trim();
  return shipDatabase.filter(ship => 
    ship.size?.toLowerCase() === normalizedSize
  );
};

export const getShipsByRole = (role: string): ShipDetails[] => {
  if (!role) return [];
  const normalizedRole = role.toLowerCase().trim();
  return shipDatabase.filter(ship => 
    ship.role?.some(r => r.toLowerCase().includes(normalizedRole))
  );
};

// Ship data organized by manufacturer
export const shipManufacturers: ShipManufacturer[] = [
  {
    name: "Aegis Dynamics",
    ships: [
      { name: "Avenger Stalker", image: formatShipImageName("Avenger Stalker") },
      { name: "Avenger Titan", image: formatShipImageName("Avenger Titan") },
      { name: "Avenger Titan Renegade", image: formatShipImageName("Avenger Titan Renegade") },
      { name: "Avenger Warlock", image: formatShipImageName("Avenger Warlock") },
      { name: "Eclipse", image: formatShipImageName("Eclipse") },
      { name: "Gladius", image: formatShipImageName("Gladius") },
      { name: "Gladius Pirate", image: formatShipImageName("Gladius Pirate") },
      { name: "Gladius Valiant", image: formatShipImageName("Gladius Valiant") },
      { name: "Hammerhead", image: formatShipImageName("Hammerhead") },
      { name: "Hammerhead Best In Show Edition", image: formatShipImageName("Hammerhead Best In Show Edition") },
      { name: "Idris-K", image: formatShipImageName("Idris-K") },
      { name: "Idris-M", image: formatShipImageName("Idris-M") },
      { name: "Idris-P", image: formatShipImageName("Idris-P") },
      { name: "Javelin", image: formatShipImageName("Javelin") },
      { name: "Nautilus", image: formatShipImageName("Nautilus") },
      { name: "Reclaimer", image: formatShipImageName("Reclaimer") },
      { name: "Reclaimer Best In Show Edition", image: formatShipImageName("Reclaimer Best In Show Edition") },
      { name: "Redeemer", image: formatShipImageName("Redeemer") },
      { name: "Retaliator", image: formatShipImageName("Retaliator") },
      { name: "Sabre", image: formatShipImageName("Sabre") },
      { name: "Sabre Comet", image: formatShipImageName("Sabre Comet") },
      { name: "Sabre Firebird", image: formatShipImageName("Sabre Firebird") },
      { name: "Sabre Peregrine", image: formatShipImageName("Sabre Peregrine") },
      { name: "Sabre Raven", image: formatShipImageName("Sabre Raven") },
      { name: "Vanguard Harbinger", image: formatShipImageName("Vanguard Harbinger") },
      { name: "Vanguard Hoplite", image: formatShipImageName("Vanguard Hoplite") },
      { name: "Vanguard Sentinel", image: formatShipImageName("Vanguard Sentinel") },
      { name: "Vulcan", image: formatShipImageName("Vulcan") }
    ]
  },
  {
    name: "Anvil Aerospace",
    ships: [
      { name: "Arrow", image: formatShipImageName("Arrow") },
      { name: "Ballista", image: formatShipImageName("Ballista") },
      { name: "Ballista Dunestalker", image: formatShipImageName("Ballista Dunestalker") },
      { name: "Ballista Snowblind", image: formatShipImageName("Ballista Snowblind") },
      { name: "C8R Pisces Rescue", image: formatShipImageName("C8R Pisces Rescue") },
      { name: "C8X Pisces Expedition", image: formatShipImageName("C8X Pisces Expedition") },
      { name: "Carrack", image: formatShipImageName("Carrack") },
      { name: "Carrack Expedition", image: formatShipImageName("Carrack Expedition") },
      { name: "Centurion", image: formatShipImageName("Centurion") },
      { name: "Crucible", image: formatShipImageName("Crucible") },
      { name: "F7C Hornet Mk I", image: formatShipImageName("F7C Hornet Mk I") },
      { name: "F7C Hornet Mk II", image: formatShipImageName("F7C Hornet Mk II") },
      { name: "F7C Hornet Wildfire Mk I", image: formatShipImageName("F7C Hornet Wildfire Mk I") },
      { name: "F7C-M Hornet Heartseeker Mk II", image: formatShipImageName("F7C-M Hornet Heartseeker Mk II") },
      { name: "F7C-M Super Hornet Heartseeker Mk I", image: formatShipImageName("F7C-M Super Hornet Heartseeker Mk I") },
      { name: "F7C-M Super Hornet Mk I", image: formatShipImageName("F7C-M Super Hornet Mk I") },
      { name: "F7C M Super Hornet Mk II", image: formatShipImageName("F7C M Super Hornet Mk II") },
      { name: "F7C-R Hornet Tracker Mk I", image: formatShipImageName("F7C-R Hornet Tracker Mk I") },
      { name: "F7C-R Hornet Tracker Mk II", image: formatShipImageName("F7C-R Hornet Tracker Mk II") },
      { name: "F7C-S Hornet Ghost Mk I", image: formatShipImageName("F7C-S Hornet Ghost Mk I") },
      { name: "F7C-S Hornet Ghost Mk II", image: formatShipImageName("F7C-S Hornet Ghost Mk II") },
      { name: "F8C Lightening", image: formatShipImageName("F8C Lightening") },
      { name: "Gladiator", image: formatShipImageName("Gladiator") },
      { name: "Hawk", image: formatShipImageName("Hawk") },
      { name: "Hurricane", image: formatShipImageName("Hurricane") },
      { name: "Legionnaire", image: formatShipImageName("Legionnaire") },
      { name: "Liberator", image: formatShipImageName("Liberator") },
      { name: "Paladin", image: formatShipImageName("Paladin") },
      { name: "Spartan", image: formatShipImageName("Spartan") },
      { name: "Terrapin", image: formatShipImageName("Terrapin") },
      { name: "Terrapin Medic", image: formatShipImageName("Terrapin Medic") },
      { name: "Valkyrie", image: formatShipImageName("Valkyrie") },
      { name: "Valkyrie Liberator", image: formatShipImageName("Valkyrie Liberator") }
    ]
  },
  {
    name: "Aopoa",
    ships: [
      { name: "Blade", image: formatShipImageName("Blade") },
      { name: "Khartu-al", image: formatShipImageName("Khartu-al") },
      { name: "Nox", image: formatShipImageName("Nox") },
      { name: "Nox Kue", image: formatShipImageName("Nox Kue") },
      { name: "San'tok.yāi", image: formatShipImageName("San'tok.yāi") },
      { name: "Scythe", image: formatShipImageName("Scythe") }
    ]
  },
  {
    name: "Argo Astronautics",
    ships: [
      { name: "ATLS", image: formatShipImageName("ATLS") },
      { name: "ATLS GEO", image: formatShipImageName("ATLS GEO") },
      { name: "CSV-SM", image: formatShipImageName("CSV-SM") },
      { name: "MPUV Cargo", image: formatShipImageName("MPUV Cargo") },
      { name: "MPUV Personnel", image: formatShipImageName("MPUV Personnel") },
      { name: "MPUV Tractor", image: formatShipImageName("MPUV Tractor") },
      { name: "MOLE", image: formatShipImageName("MOLE") },
      { name: "MOLE Carbon", image: formatShipImageName("MOLE Carbon") },
      { name: "MOLE Talus", image: formatShipImageName("MOLE Talus") },
      { name: "RAFT", image: formatShipImageName("RAFT") },
      { name: "SRV", image: formatShipImageName("SRV") }
    ]
  },
  {
    name: "Banu",
    ships: [
      { name: "Defender", image: formatShipImageName("Defender") },
      { name: "Merchantman", image: formatShipImageName("Merchantman") }
    ]
  },
  {
    name: "CNOU (Consolidated Outland)",
    ships: [
      { name: "HoverQuad", image: formatShipImageName("HoverQuad") },
      { name: "Nomad", image: formatShipImageName("Nomad") },
      { name: "Pioneer", image: formatShipImageName("Pioneer") },
      { name: "Mustang Alpha", image: formatShipImageName("Mustang Alpha") },
      { name: "Mustang Alpha Vindicator", image: formatShipImageName("Mustang Alpha Vindicator") },
      { name: "Mustang Beta", image: formatShipImageName("Mustang Beta") },
      { name: "Mustang Delta", image: formatShipImageName("Mustang Delta") },
      { name: "Mustang Gamma", image: formatShipImageName("Mustang Gamma") },
      { name: "Mustang Omega", image: formatShipImageName("Mustang Omega") }
    ]
  },
  {
    name: "Crusader Industries",
    ships: [
      { name: "A1 Spirit", image: formatShipImageName("A1 Spirit") },
      { name: "A2 Hercules Starlifter", image: formatShipImageName("A2 Hercules Starlifter") },
      { name: "Ares Star Fighter Inferno", image: formatShipImageName("Ares Star Fighter Inferno") },
      { name: "Ares Star Fighter Ion", image: formatShipImageName("Ares Star Fighter Ion") },
      { name: "C1 Spirit", image: formatShipImageName("C1 Spirit") },
      { name: "C2 Hercules Starlifter", image: formatShipImageName("C2 Hercules Starlifter") },
      { name: "E1 Spirit", image: formatShipImageName("E1 Spirit") },
      { name: "Genesis Starliner", image: formatShipImageName("Genesis Starliner") },
      { name: "Intrepid", image: formatShipImageName("Intrepid") },
      { name: "M2 Hercules Starlifter", image: formatShipImageName("M2 Hercules Starlifter") },
      { name: "Mercury Star Runner", image: formatShipImageName("Mercury Star Runner") }
    ]
  },
  {
    name: "Drake Interplanetary",
    ships: [
      { name: "Buccaneer", image: formatShipImageName("Buccaneer") },
      { name: "Caterpillar", image: formatShipImageName("Caterpillar") },
      { name: "Caterpillar Best In Show Edition", image: formatShipImageName("Caterpillar Best In Show Edition") },
      { name: "Caterpillar Pirate Edition", image: formatShipImageName("Caterpillar Pirate Edition") },
      { name: "Corsair", image: formatShipImageName("Corsair") },
      { name: "Cutlass Black", image: formatShipImageName("Cutlass Black") },
      { name: "Cutlass Black Best In Show Edition", image: formatShipImageName("Cutlass Black Best In Show Edition") },
      { name: "Cutlass Blue", image: formatShipImageName("Cutlass Blue") },
      { name: "Cutlass Red", image: formatShipImageName("Cutlass Red") },
      { name: "Cutlass Steel", image: formatShipImageName("Cutlass Steel") },
      { name: "Cutter", image: formatShipImageName("Cutter") },
      { name: "Cutter Rambler", image: formatShipImageName("Cutter Rambler") },
      { name: "Cutter Scout", image: formatShipImageName("Cutter Scout") },
      { name: "Dragonfly", image: formatShipImageName("Dragonfly") },
      { name: "Dragonfly Yellowjacket", image: formatShipImageName("Dragonfly Yellowjacket") },
      { name: "Golem", image: formatShipImageName("Golem") },
      { name: "Herald", image: formatShipImageName("Herald") },
      { name: "Ironclad", image: formatShipImageName("Ironclad") },
      { name: "Ironclad Assault", image: formatShipImageName("Ironclad Assault") },
      { name: "Kraken", image: formatShipImageName("Kraken") },
      { name: "Kraken Privateer", image: formatShipImageName("Kraken Privateer") },
      { name: "Mule", image: formatShipImageName("Mule") },
      { name: "Vulture", image: formatShipImageName("Vulture") }
    ]
  },
  {
    name: "Esperia",
    ships: [
      { name: "Glaive", image: formatShipImageName("Glaive") },
      { name: "Prowler", image: formatShipImageName("Prowler") },
      { name: "Talon", image: formatShipImageName("Talon") },
      { name: "Talon Shrike", image: formatShipImageName("Talon Shrike") }
    ]
  },
  {
    name: "Gatac Manufacture",
    ships: [
      { name: "Railen", image: formatShipImageName("Railen") },
      { name: "Syulen", image: formatShipImageName("Syulen") }
    ]
  },
  {
    name: "Greycat Industrial",
    ships: [
      { name: "MTC", image: formatShipImageName("MTC") },
      { name: "PTV", image: formatShipImageName("PTV") },
      { name: "ROC", image: formatShipImageName("ROC") },
      { name: "ROC-DS", image: formatShipImageName("ROC-DS") },
      { name: "STV", image: formatShipImageName("STV") },
      { name: "Ursa", image: formatShipImageName("Ursa") },
      { name: "Ursa Fortuna", image: formatShipImageName("Ursa Fortuna") },
      { name: "Ursa Medivac", image: formatShipImageName("Ursa Medivac") }
    ]
  },
  {
    name: "Kruger Intergalatic",
    ships: [
      { name: "P-52 Merlin", image: formatShipImageName("P-52 Merlin") },
      { name: "P-72 Archimedes", image: formatShipImageName("P-72 Archimedes") },
      { name: "P-72 Archimedes Emerald", image: formatShipImageName("P-72 Archimedes Emerald") }
    ]
  },
  {
    name: "MISC (Musashi Industrial and Starflight Concern)",
    ships: [
      { name: "Endeavor", image: formatShipImageName("Endeavor") },
      { name: "Expanse", image: formatShipImageName("Expanse") },
      { name: "Fortune", image: formatShipImageName("Fortune") },
      { name: "Freelancer", image: formatShipImageName("Freelancer") },
      { name: "Freelancer DUR", image: formatShipImageName("Freelancer DUR") },
      { name: "Freelancer MAX", image: formatShipImageName("Freelancer MAX") },
      { name: "Freelancer MIS", image: formatShipImageName("Freelancer MIS") },
      { name: "Hull A", image: formatShipImageName("Hull A") },
      { name: "Hull B", image: formatShipImageName("Hull B") },
      { name: "Hull C", image: formatShipImageName("Hull C") },
      { name: "Hull D", image: formatShipImageName("Hull D") },
      { name: "Hull E", image: formatShipImageName("Hull E") },
      { name: "Odyssey", image: formatShipImageName("Odyssey") },
      { name: "Prospector", image: formatShipImageName("Prospector") },
      { name: "Razor", image: formatShipImageName("Razor") },
      { name: "Razor EX", image: formatShipImageName("Razor EX") },
      { name: "Razor LX", image: formatShipImageName("Razor LX") },
      { name: "Reliant Kore", image: formatShipImageName("Reliant Kore") },
      { name: "Reliant Mako", image: formatShipImageName("Reliant Mako") },
      { name: "Reliant Sen", image: formatShipImageName("Reliant Sen") },
      { name: "Reliant Tana", image: formatShipImageName("Reliant Tana") },
      { name: "Starfarer", image: formatShipImageName("Starfarer") },
      { name: "Starfarer Gemini", image: formatShipImageName("Starfarer Gemini") },
      { name: "Starlancer MAX", image: formatShipImageName("Starlancer MAX") },
      { name: "Starlancer TAC", image: formatShipImageName("Starlancer TAC") }
    ]
  },
  {
    name: "Mirai",
    ships: [
      { name: "Fury", image: formatShipImageName("Fury") },
      { name: "Fury LX", image: formatShipImageName("Fury LX") },
      { name: "Fury MX", image: formatShipImageName("Fury MX") },
      { name: "G12", image: formatShipImageName("G12") },
      { name: "G12a", image: formatShipImageName("G12a") },
      { name: "G12r", image: formatShipImageName("G12r") },
      { name: "Guardian", image: formatShipImageName("Guardian") },
      { name: "Guardian MX", image: formatShipImageName("Guardian MX") },
      { name: "Guardian QI", image: formatShipImageName("Guardian QI") },
      { name: "Pulse", image: formatShipImageName("Pulse") },
      { name: "Pulse LX", image: formatShipImageName("Pulse LX") }
    ]
  },
  {
    name: "Origin Jumpworks",
    ships: [
      { name: "100i", image: formatShipImageName("100i") },
      { name: "125a", image: formatShipImageName("125a") },
      { name: "135c", image: formatShipImageName("135c") },
      { name: "300i", image: formatShipImageName("300i") },
      { name: "315p", image: formatShipImageName("315p") },
      { name: "325a", image: formatShipImageName("325a") },
      { name: "350r", image: formatShipImageName("350r") },
      { name: "400i", image: formatShipImageName("400i") },
      { name: "600i Explorer", image: formatShipImageName("600i Explorer") },
      { name: "600i Touring", image: formatShipImageName("600i Touring") },
      { name: "85x", image: formatShipImageName("85x") },
      { name: "890 Jump", image: formatShipImageName("890 Jump") },
      { name: "M50", image: formatShipImageName("M50") },
      { name: "X1", image: formatShipImageName("X1") },
      { name: "X1 Force", image: formatShipImageName("X1 Force") },
      { name: "X1 Velocity", image: formatShipImageName("X1 Velocity") }
    ]
  },
  {
    name: "Roberts Space Industries (RSI)",
    ships: [
      { name: "Apollo Medivac", image: formatShipImageName("Apollo Medivac") },
      { name: "Apollo Triage", image: formatShipImageName("Apollo Triage") },
      { name: "Arrastra", image: formatShipImageName("Arrastra") },
      { name: "Aurora CL", image: formatShipImageName("Aurora CL") },
      { name: "Aurora ES", image: formatShipImageName("Aurora ES") },
      { name: "Aurora LN", image: formatShipImageName("Aurora LN") },
      { name: "Aurora LX", image: formatShipImageName("Aurora LX") },
      { name: "Aurora MR", image: formatShipImageName("Aurora MR") },
      { name: "Constellation Andromeda", image: formatShipImageName("Constellation Andromeda") },
      { name: "Constellation Aquila", image: formatShipImageName("Constellation Aquila") },
      { name: "Constellation Phoenix", image: formatShipImageName("Constellation Phoenix") },
      { name: "Constellation Phoenix Emerald", image: formatShipImageName("Constellation Phoenix Emerald") },
      { name: "Constellation Taurus", image: formatShipImageName("Constellation Taurus") },
      { name: "Galaxy", image: formatShipImageName("Galaxy") },
      { name: "Lynx", image: formatShipImageName("Lynx") },
      { name: "Mantis", image: formatShipImageName("Mantis") },
      { name: "Orion", image: formatShipImageName("Orion") },
      { name: "Perseus", image: formatShipImageName("Perseus") },
      { name: "Polaris", image: formatShipImageName("Polaris") },
      { name: "Scorpius", image: formatShipImageName("Scorpius") },
      { name: "Scorpius Antares", image: formatShipImageName("Scorpius Antares") },
      { name: "Zeus Mk II CL", image: formatShipImageName("Zeus Mk II CL") },
      { name: "Zeus Mk II ES", image: formatShipImageName("Zeus Mk II ES") },
      { name: "Zeus Mk II MR", image: formatShipImageName("Zeus Mk II MR") }
    ]
  },
  {
    name: "Tumbril Land Systems",
    ships: [
      { name: "Cyclone", image: formatShipImageName("Cyclone") },
      { name: "Cyclone AA", image: formatShipImageName("Cyclone AA") },
      { name: "Cyclone MT", image: formatShipImageName("Cyclone MT") },
      { name: "Cyclone RC", image: formatShipImageName("Cyclone RC") },
      { name: "Cyclone RN", image: formatShipImageName("Cyclone RN") },
      { name: "Cyclone TR", image: formatShipImageName("Cyclone TR") },
      { name: "Nova", image: formatShipImageName("Nova") },
      { name: "Storm", image: formatShipImageName("Storm") },
      { name: "Storm AA", image: formatShipImageName("Storm AA") }
    ]
  },
  {
    name: "Vanduul",
    ships: [
      { name: "Scythe", image: formatShipImageName("Scythe") }
    ]
  }
];

// Get the list of all manufacturers for the dropdown
export const getManufacturersList = (): string[] => {
  return shipManufacturers.map(manufacturer => manufacturer.name);
};

// Get ships for a specific manufacturer
export const getShipsByManufacturer = (manufacturerName: string): Ship[] => {
  const manufacturer = shipManufacturers.find(m => m.name === manufacturerName);
  return manufacturer ? manufacturer.ships : [];
}; 